affiliation_to_country = {
    "Carnegie Mellon University": "US",
    "University of Toronto": "CA",
    "Purdue University": "US",
    "Colfax Research": "US",
    "University of Alberta": "CA",
    "University of Illinois at Urbana-Champaign": "US",
    "Air Force Research Laboratory": "US",
    "Johns Hopkins University": "US",
    "University of York": "GB",
    "Shanghai Jiao Tong University": "CN",
    "University of California-San Diego": "US",
    "University of Miami": "US",
    "University of California - Berkeley": "US",
    "University of California-Los Angeles": "US",
    "Brown University": "US",
    "University of California-Santa Cruz": "US",
    "W. M. Keck Science Department": "US",
    "IIIT Hyderabad": "IN",
    "Hebei Normal University": "CN",
    "Columbia University": "US",
    "Indiana University at Bloomington": "US",
    "Queen Mary University of London": "GB",
    "TU Dortmund University": "DE",
    "University of Hawaii at Manoa": "US",
    "Univ. of Illinois at Urbana-Champaign": "US",
    "University of Utah": "US",
    "University of Maryland College Park": "US",
    "Constructor University": "DE",
    "Massachusetts Institute of Technology": "US",
    "Stanford University": "US",
    "Technion": "IL",
    "Harbin Institute of Technology": "CN",
    "University of New Hampshire": "US",
    "Texas A&M University Main Campus": "US",
    "KU Leuven": "BE",
    "Hebrew University of Jerusalem": "IL",
    "Oregon State University": "US",
    "None": "UNK",  # No affiliation provided
    "University of Michigan": "US",
    "University of Washington": "US",
    "Rutgers University": "US",
    "Cheetah Mobile": "CN",
    "US DEVCOM Army Research Laboratory": "US",
    "CWI": "NL",
    "PUC-RIO": "BR",
    "California Institute of Technology": "US",
    "Princeton University": "US",
    "University of Colorado at Boulder": "US",
    "South China University of Technology": "CN",
    "University of Virginia Main Campus": "US",
    "InVivo AI": "US",
    "Magnum Engine": "US",
    "Futureverse": "US",
    "DJI Innovations": "CN",
    "NYU Langone Medical Center": "US",
    "UMass Chan Medical School Neurobiology Department": "US",
    "University of Nevada, Reno": "US",
    "Sioux Technology": "US",
    "Universidad Politécnica de Cataluna": "ES",
    "Northern Kentucky University": "US",
    "Safran Electronics and Defense Australasia": "AU",
    "University of Cincinnati": "US",
    "Honda Research Institute USA, Inc.": "US",
    "Benaroya Research Institute ": "US",
    "Raive": "US",
    "feedzai": "PT",
    "Baylor College of Medicine": "US",
    "Kakao Brain": "KR",
    "University of Massachusetts at Lowell": "US",
    "Nutanix": "US",
    "Upwork Inc": "US",
    "Ethical AI Novelties": "US",
    "Citadel Securities": "US",
    "Invertible AI": "US",
    "inspur": "CN",
    "DENSO CORPORATION": "JP",
    "Biomap": "US",
    "Monash University": "AU",
    "MPG Ranch": "US",
    "Cainao Netwok": "CN",
    "Alipay": "CN",
    "Marquette University": "US",
    "Zebra Technologies": "US",
    "University of Oklahoma": "US",
    "Operant Biopharma": "US",
    "University of the District of Columbia": "US",
    "Telefonica Research": "ES",
    "UMass Chan Medical School": "US",
    "National Institute of Standards and Technology": "US",
    "The Hong Kong University of Science and Technology (Guangzhou)": "CN",
    "Brigham Young University": "US",
    "Apart Research": "US",
    "LiAuto": "CN",
    "Xiaohongshu": "CN",
    "Wesleyan University": "US",
    "Qatar Computing Research Institute": "QA",
    "China Nanhu Academy of Electronics and Information Technology": "CN",
    "sapeon": "KR",
    "Fujian(Quanzhou)Advanced Manufacturing Institute": "CN",
    "Nippon Telegraph and Telephone Corporation": "JP",
    "Bytedance Inc.": "CN",
    "Xiaomi ": "CN",
    "Cainiao Network": "CN",
    "Ericsson Canada": "CA",
    "Academic medical center at State University of New York at Stony Brook": "US",
    "Inner Mongolia University of Technology": "CN",
    "Medidata Solutions": "US",
    "Louisiana State University": "US",
    "Kuang-chi Institute of Advanced Technology": "TW",
    "XiaomiCamera": "CN",
    "TU Munich": "DE",
    "Xi'an Jiaotong University": "CN",
    "University of Louisiana at Lafayette": "US",
    "SenseTime Research": "CN",
    "Picsart": "US",
    "North South University": "BD",
    "CaiNiao Network": "CN",
    "Aleph Alpha": "DE",
    "Case Western Reserve University": "US",
    "VMware Research": "US",
    "HP Inc.": "US",
    "Wipro Technologies": "IN",
    "Harvey Mudd College": "US",
    "Capital One": "US",
    "Optum Labs": "US",
    "Xiaomi": "CN",
    "Institue for Advanced Study, Princeton": "US",
    "Universitat Rovira i Virgili": "ES",
    "Southern Methodist University, Southern Methodist University": "US",
    "Aleph-Alpha gmbh": "DE",
    "OxAI Safety Hub": "GB",
    "Shanghai Newtouch  Software  Co. Ltd": "CN",
    "Wormpex AI Research": "US",
    "FaunaPhotonics": "US",
    "Artificial Intelligence Research Institute": "US",
    "Central European University": "HU",
    "Woven Planet": "JP",
    "Machine Discovery": "US",
    "Northeastern University": "US",
    "tsinghua university": "CN",
    "STOCKTON UNIVERSITY": "US",
    "Tennessee State University": "US",
    "Washington University in St. Louis": "US",
    "University of Texas at Dallas": "US",
    "Enrich Biosystems": "US",
    "National Research University Higher School of Economics": "RU",
    "Peking Union Medical Collage": "CN",
    "KakaoBrain": "KR",
    "University of the Basque Country (UPV/EHU)": "ES",
    "Panasonic Corporation": "JP",
    "BIT": "CN",
    "YerevaNN research Lab": "US",
    "pfizer": "US",
    "Institute of Physics, Henan Academy of Sciences": "CN",
    "NIO": "CN",
    "Universidad del País Vasco": "ES",
    "Sambanova Systems Inc.": "US",
    "Araya": "US",
    "Valve Corporation": "US",
    "Orcam": "IL",
    "Independant": "US",
    "Tilburg University": "NL",
    "KonanAI": "JP",
    "Collov Research": "US",
    "OneFlow Inc.": "US",
    "Oberlin College": "US",
    "Chongqing University of Posts and Telecommunications": "CN",
    "Iowa State University": "US",
    "Auburn University": "US",
    "University of Maine": "US",
    "Cellarity Inc": "US",
    "AntFin": "CN",
    "Cloudwise Research": "US",
    "Nanjing Tech University": "CN",
    "Mobileye": "IL",
    "NatInLab": "US",
    "Champalimaud Foundation": "PT",
    "Ecole Polytechnique": "FR",
    "Carlmont High School": "US",
    "University of Nevada, Reno, University of Nevada, Reno": "US",
    "BioMap": "US",
    "China Mobile research institute": "CN",
    "Picsart AI Research": "US",
    "Hikvision Research Institute": "CN",
    "Google DeepMind": "GB",
    "Ubisoft": "FR",
    "University of Texas Southwestern Medical Center": "US",
    "Sano - Centre for Personalised Computational Medicine": "US",
    "National Taiwan University": "TW",
    "MERCK & CO., INC.": "US",
    "Synerise S.A.": "PL",
    "Lynbrook High School": "US",
    "xiaohongshu": "CN",
    "Telefonica": "ES",
    "Xpeng Motors": "CN",
    "QCRI": "QA",
    "Dongguk University": "KR",
    "Howard University": "US",
    "Ant Group": "CN",
    "XSense.ai Inc.": "US",
    "United Automotive Electronic Systems": "CN",
    "National University of Singapore": "SG",
    "University of Louisiana at Lafeyette": "US",
    "Portland State University": "US",
    "Southeast University": "CN",
    "International School of Zug and Luzern": "CH",
    "China Mobile Research Institute": "CN",
    "University of Hawaii": "US",
    "Artificial Intelligence Research Institute (AIRI)": "US",
    "Huazhong University of Science and Technology": "CN",
    "Line Corp": "JP",
    "AI21 Labs": "IL",
    "AXA": "FR",
    "Operant BioPharma": "US",
    "Ximalaya Inc., China": "CN",
    "Georgia State University": "US",
    "University of Kentucky": "US",
    "Ximalaya Inc.": "CN",
    "LG Display": "KR",
    "Western Washington University": "US",
    "AIRI": "US",
    "IMT Atlantique": "FR",
    "Apziva": "US",
    "Hallmark University": "US",
    "TomTom": "NL",
    "Zebra technologies": "US",
    "Nostrum Biodiscovery": "US",
    "CJ Corporation": "KR",
    "Feedzai": "PT",
    "Siemens Corporate Research": "US",
    "SUNY Upstate Medical University": "US",
    "International Technological University": "US",
    "University of Guelph": "CA",
    "Independent": "US",
    "Evidation Health": "US",
    "Hippocratic AI": "US",
    "Illinois Institute of Technology": "US",
    "TianyiJiaotong Technology": "CN",
    "IMDEA Networks": "ES",
    "Yahoo": "US",
    "Zscaler": "US",
    "Nanhu Academy of Electronics and Information Technology": "CN",
    "MIT": "US",
    "Crofton House School": "CA",
    "Brac University": "BD",
    "Ocado Technology": "GB",
    "Li Auto": "CN",
    "Wise Plc": "GB",
    "Coral Gardeners": "US",
    "Aleph Alpha GmbH": "DE",
    "University of Pennsylvania": "US",
    "Center for Advanced Systems Understanding": "DE",
    "InfAI": "DE",
    "New York Institute of Technology": "US",
    "University of Vermont": "US",
    "Woods Hole Oceanographic Institution": "US",
    "Augment Computing": "US",
    "Southern Methodist University": "US",
    "Idemia Identity & Security": "FR",
    "UT Southwestern Medical Center": "US",
    "Kennesaw State University": "US",
    "Find & Order": "US",
    "Imperial College London": "GB",
    "Volkswagen Group Innovation": "DE",
    "Babban Gona": "NG",
    "United Automotive Electronic Systems Co., Ltd.": "CN",
    "Kakaobrain": "KR",
    "XiaoHongshu": "CN",
    "https://xinchenai.com/": "CN",
    "UAES": "CN",
    "Cerence GmbH": "DE",
    "Yahoo Research": "US",
    "YerevaNN Research Lab": "US",
    "Slb": "US",
    "Datakalab": "US",
    "Hebei University of Science & Technology": "CN",
    "Scaled Cognition": "US",
    "Emory University": "US",
    "shxmxn": "CN",
    "eBay Research": "US",
    "Wright State University": "US",
    "Cleveland State University": "US",
    "Hochschule München": "DE",
    "Innopolis University": "RU",
    "Jadavpur University": "IN",
    "Tongdun Technology Company Limited": "CN",
    "The Harker School": "US",
    "City of Hope": "US",
    "Indiana University": "US",
    "Wellesley College": "US",
    "University of Science and Technology of China": "CN",
    "DeepSeek AI": "US",
    "EQT": "SE",
    "Avatar Cognition": "US",
    "Splunk": "US",
    "Astroinformatics, HITS gGmbH, Heidelberg, Germany": "DE",
    "Inventec Corporation": "TW",
    "Champalimaud Centre for the Unknown": "PT",
    "NIST": "US",
    "FPT Software AI Center": "VN",
    "Intuit": "US",
    "Basque Center for Applied Mathematics": "ES",
    "University of Miami, University of Miami": "US",
    "University of California Berkeley": "US",
    "Ensem Therapeutics": "US",
    "state grid of china": "CN",
    "IMDEA Networks Institute": "ES",
    "Insitro": "US",
    "Tulane University": "US",
    "Austin Peay State University": "US",
    "Inventec Inc.": "TW",
    "HHMI Janelia Research Campus": "US",
    "NCSOFT": "KR",
    "Southern Illinois University-Carbondale": "US",
    "National Yang Ming Chiao Tung University": "TW",
    "Michigan Technological University": "US",
    "kakaobrain": "KR",
    "Hilabs Inc": "US",
    "University of Memphis": "US",
    "The Chinese University of Hong Kong, Shenzhen": "CN",
    "Texas Tech University": "US",
    "San Francisco State University": "US",
    "Spin-Quantum Co. LTD.": "CN",
    "Find&Order": "US",
    "NYU Langone": "US",
    "Carenostics": "US",
    "LG Electronics": "KR",
    "VW IECC": "DE",
    "Air Liquide": "FR",
    "LG Display Co., Ltd.": "KR",
    "Carnegie-Mellon University": "US",
    "Heidelberg Institute for Theoretical Studies": "DE",
    "SIG": "US",
    "Kakao Brain Corp.": "KR",
    "Saginaw Valley State University": "US",
    "VIVE STUDIOS": "TW",
    "Kakao Brain Corp": "KR",
    "University of Massachusetts, Boston": "US",
    "ItalAI S.R.L.": "IT",
    "Fordham University": "US",
    "NAVER WEBTOON": "KR",
    "University of Colorado at Denver": "US",
    "Worcester Polytechnic Institute": "US",
    "Indiana University, Bloomington": "US",
    "University of Massachusetts, Lowell": "US",
    "Zhihu": "CN",
    "Drexel University": "US",
    "AISIN SOFTWARE Co., Ltd.": "JP",
    "Mississippi State University": "US",
    "Pfizer": "US",
    "Bloomberg AI": "US",
    "Senslab Technology Co.,Ltd.": "CN",
    "Zhejiang Lab": "CN",
    "Academy of Military Science": "CN",
    "Information Sciences Institute": "US",
    "Ericsson": "SE",
    "University of Chinese Academy of Sciences": "CN",
    "Cactus Communications": "US",
    "Pendulum Systems": "US",
    "NEC": "JP",
    "Hyundai Motor Company": "KR",
    "Sambanova Systems, Inc": "US",
    "CMU, Carnegie Mellon University": "US",
    "Ca' Foscari University of Venice": "IT",
    "Cadence Design Systems": "US",

    "Leeroo AI": "GB",
    "University of Michigan Ann Arbor": "US",
    "Luis Villa Law": "US",
    "Two Sigma": "US",
    "POSCO HOLDINGS": "KR",
    "Valeo": "FR",
    "Sichuan University": "CN",
    "Cornell University": "US",
    "Moscow Institute of Physics and Technology": "RU",
    "xiaomi corporation": "CN",
    "Singapore Management University": "SG",
    "RTE France": "FR",
    "Harvard Business School": "US",
    "MiHoYo": "CN",
    "SambaNova Systems": "US",
    "Wake Forest Baptist Health": "US",
    "Trustees of Boston University": "US",
    "City University of New York": "US",
    "University of Texas Health Center at Houson": "US",
    "Moonshot Marketing": "IN",
    "Hong Kong University of Science and Technology (GuangZhou)": "CN",
    "Volkswagen AG": "DE",
    "UnSearch": "UNK",
    "baichuan": "CN",
    "Federal Reserve Bank of Chicago": "US",
    "University of California-Berkeley": "US",
    "Verily": "US",
    "Upstream CFD GmbH": "DE",
    "University of New Haven": "US",
    "Georgia Tech Research Corporation": "US",
    "Deep Learning Indaba": "ZA",
    "XtalPi": "CN",
    "Sensetime  Research": "CN",
    "Panasonic Connect": "JP",
    "Baichuan Inc.": "CN",
    "Johnson and Johnson": "US",
    "Siemens Energy": "DE",
    "New College of Florida": "US",
    "University of Massachusetts Amherst": "US",
    "Department of Software Engineering, Shenzhen University": "CN",
    "Hewlett Packard Labs @ Hewlett Packard Enterprise": "US",
    "Deezer": "FR",
    "Uber": "US",
    "KC-ML2": "KR",
    "Universidad Politécnica de Catalunya": "ES",
    "Profluent Bio": "US",
    "Changan Automobile": "CN",
    "Pennsylvania State Univ University Park": "US",
    "Shenzhen University": "CN",
    "Lapis Labs": "US",
    "Bayer Ag": "DE",
    "MD Anderson Cancer Center": "US",
    "Johnson & Johnson": "US",
    "Antgroup": "CN",
    "National Renewable Energy Lab": "US",
    "Max Planck Institute for Security and Privacy": "DE",
    "Happy Elements": "CN",
    "KC Machine Learning Lab": "KR",
    "vivestudios": "KR",
    "MercadoLibre Inc.": "AR",
    "Michigan State University": "US",
    "University of Iowa": "US",
    "insitro": "US",
    "Harvard University": "US",
    "Upstream CFD": "DE",
    "Mila, UdeM": "CA",
    "Quantinuum Ltd.": "US",
    "lowRISC": "GB",
    "California Polytechnic State University, Pomona": "US",
    "Tsinghua University": "CN",
    "BigHat Biosciences": "US",
    "DatologyAI": "US",
    "deepwisdom": "CN",
    "Elsevier": "NL",
    "Bose": "US",
    "Colorado School of Mines": "US",
    "Memorial Sloan Kettering Cancer Centre": "US",
    "CVTE Research Institute": "CN",
    "SenseAuto Research": "CN",
    "University of Texas Health Science Center at Houston": "US",
    "Huawei": "CN",
    "Stellarrover.Inc": "CN",
    "University of Houston": "US",
    "HippocraticAI": "US",
    "Thalesians Marine Ltd, the AI in shipping and logistics company": "GB",
    "MosaicML": "US",
    "Infinigence": "UNK",
    "Crowdstrike Holdings Inc": "US",
    "Duke University": "US",
    "CUNY Queens College": "US",
    "NTT": "JP",
    "Hewlett Packard Enterprise": "US",
    "Boeing Research and Technology Software ": "US",
    "Dexcom, Inc.": "US",
    "Goethe University Frankfurt, Germany": "DE",
    "Air Force Research Laboratory, Information Directorate": "US",
    "United States Naval Academy": "US",
    "James Madison University": "US",
    "lastminute.com group": "GB",
    "constructor university": "DE",
    "Xiaohongshu Inc": "CN",
    "University College London": "GB",
    "Fidelity Investments": "US",
    "Rutgers University New Brunswick": "US",
    "Catalan Institute of Advanced Studies": "ES",
    "Fred Hutchinson Cancer Research Center": "US",
    "Flagship Pioneering": "US",
    "Albert Einstein College of Medicine, Inc.": "US",
    "China Mobile (Suzhou) Software Technology Company": "CN",
    "AppTek GmbH": "DE",
    "Shopee": "SG",
    "Indiana University Purdue University Indianapolis": "US",
    "Laboratory for Advanced Computing and  Intelligence Engineering": "US",
    "Earth Species Project": "US",
    "Indiana State University ": "US",
    "East China Normal University": "CN",
    "West Virginia University": "US",
    "RTE": "IE",
    "Analog Devices Inc": "US",
    "Writer": "US",
    "Baylor University": "US",
    "Xiamen BaishanCloud Technology Co., Ltd": "CN",
    "EchoX Technology Limited": "CN",
    "College of William and Mary": "US",
    "DSO National Laboratories": "SG",
    "YerevaNN research lab": "UNK",
    "Optum AI Labs": "US",
    "UC Berkeley": "US",
    "Indo Ocean Project": "UNK",
    "Max-Planck Institute for Security and Privacy": "DE",
    "Northern Arizona University": "US",
    "LG Corporation": "KR",
    "ellamind GmbH": "DE",
    "Northwestern Polytechnical University": "CN",
    "Vaneval": "UNK",
    "Microsoft Research Cambridge": "GB",
    "Genmab US Inc": "US",
    "National Open University": "IN",
    "Pinterest": "US",
    "University of Massachusetts Boston": "US",
    "InBalance": "ID",
    "Xiamen University": "CN",
    "Kinaxis inc.": "CA",
    "Predibase": "CA",
    "POSCO Holdings": "KR",
    "Leeroo": "GB",
    "Mashang Consumer Finance Co, Ltd": "CN",
    "ZOZO Research": "JP",
    "Hewlett Packard Labs": "US",
    "Verily Life Sciences": "US",
    "Panasonic Connect Co., Ltd.": "JP",
    "William Paterson University": "US",
    "USC/ISI": "US",
    "Infinigence-AI": "CN",
    "University of Alabama in Huntsville": "US",
    "POSCO holdings": "KR",
    "MoleculeMind": "US",
    "The Graduate Center, City University of New York": "US",
    "LINE Corporation": "JP",
    "Deezer Research": "FR",
    "CMRI": "IN",
    "University of North Texas": "US",
    "Quantinuum": "US",
    "CUNY Hunter College": "US",
    "Rakuten Institute of Technology": "JP",
    "Centrale Lille Alumni": "FR",
    "China Mobile Communications Company Limited Research Institute": "CN",
    "Mathematica Policy Research": "US",
    "Dimtech": "CN",
    "New Mexico State University": "US",
    "ILLUIN Technology": "FR",
    "SRI International": "US",
    "Florida Institute of Technology": "US",
    "University of California - Santa Cruz": "US",
    "eda": "UNK",
    "SaluteDevices": "US",
    "AIRI, Artificial Intelligence Research Institute": "RU"

}
