# university_country_mapping.py

# Mapping of universities and research institutions to their respective country codes
affiliation_to_country = {
    "Carnegie Mellon University": "US",
    "University of Toronto": "CA",
    "Purdue University": "US",
    "Colfax Research": "US",
    "University of Alberta": "CA",
    "University of Illinois at Urbana-Champaign": "US",
    "Air Force Research Laboratory": "US",
    "Johns Hopkins University": "US",
    "University of York": "GB",
    "Shanghai Jiao Tong University": "CN",
    "University of California-San Diego": "US",
    "University of Miami": "US",
    "University of California - Berkeley": "US",
    "University of California-Los Angeles": "US",
    "shxmxn": "UNK",  # Unknown affiliation
    "Brown University": "US",
    "University of California-Santa Cruz": "US",
    "W. M. Keck Science Department": "US",
    "IIIT Hyderabad": "IN",
    "Hebei Normal University": "CN",
    "Columbia University": "US",
    "Indiana University at Bloomington": "US",
    "Queen Mary University of London": "GB",
    "TU Dortmund University": "DE",
    "University of Hawaii at Manoa": "US",
    "Univ. of Illinois at Urbana-Champaign": "US",
    "University of Utah": "US",
    "University of Maryland College Park": "US",
    "Constructor University": "DE",
    "Massachusetts Institute of Technology": "US",
    "Stanford University": "US",
    "Technion": "IL",
    "Harbin Institute of Technology": "CN",
    "University of New Hampshire": "US",
    "Texas A&M University Main Campus": "US",
    "KU Leuven": "BE",
    "Hebrew University of Jerusalem": "IL",
    "Oregon State University": "US",
    "None": "UNK",  # No affiliation provided
    "University of Michigan": "US",
    "University of Washington": "US",
    "Rutgers University": "US",
    "Cheetah Mobile": "CN",
    "US DEVCOM Army Research Laboratory": "US",
    "CWI": "NL",
    "PUC-RIO": "BR",
    "California Institute of Technology": "US",
    "Princeton University": "US",
    "University of Colorado at Boulder": "US",
    "South China University of Technology": "CN",
    "University of Virginia Main Campus": "US"
}