affiliation_to_country = {
    "Carnegie Mellon University": "US",
    "University of Toronto": "CA",
    "Purdue University": "US",
    "Colfax Research": "US",
    "University of Alberta": "CA",
    "University of Illinois at Urbana-Champaign": "US",
    "Air Force Research Laboratory": "US",
    "Johns Hopkins University": "US",
    "University of York": "GB",
    "Shanghai Jiao Tong University": "CN",
    "University of California-San Diego": "US",
    "University of Miami": "US",
    "University of California - Berkeley": "US",
    "University of California-Los Angeles": "US",
    "Brown University": "US",
    "University of California-Santa Cruz": "US",
    "W. M. Keck Science Department": "US",
    "IIIT Hyderabad": "IN",
    "Hebei Normal University": "CN",
    "Columbia University": "US",
    "Indiana University at Bloomington": "US",
    "Queen Mary University of London": "GB",
    "TU Dortmund University": "DE",
    "University of Hawaii at Manoa": "US",
    "Univ. of Illinois at Urbana-Champaign": "US",
    "University of Utah": "US",
    "University of Maryland College Park": "US",
    "Constructor University": "DE",
    "Massachusetts Institute of Technology": "US",
    "Stanford University": "US",
    "Technion": "IL",
    "Harbin Institute of Technology": "CN",
    "University of New Hampshire": "US",
    "Texas A&M University Main Campus": "US",
    "KU Leuven": "BE",
    "Hebrew University of Jerusalem": "IL",
    "Oregon State University": "US",
    "None": "UNK",  # No affiliation provided
    "University of Michigan": "US",
    "University of Washington": "US",
    "Rutgers University": "US",
    "Cheetah Mobile": "CN",
    "US DEVCOM Army Research Laboratory": "US",
    "CWI": "NL",
    "PUC-RIO": "BR",
    "California Institute of Technology": "US",
    "Princeton University": "US",
    "University of Colorado at Boulder": "US",
    "South China University of Technology": "CN",
    "University of Virginia Main Campus": "US",
    "InVivo AI": "US",
    "Magnum Engine": "US",
    "Futureverse": "US",
    "DJI Innovations": "CN",
    "NYU Langone Medical Center": "US",
    "UMass Chan Medical School Neurobiology Department": "US",
    "University of Nevada, Reno": "US",
    "Sioux Technology": "US",
    "Universidad Politécnica de Cataluna": "ES",
    "Northern Kentucky University": "US",
    "Safran Electronics and Defense Australasia": "AU",
    "University of Cincinnati": "US",
    "Honda Research Institute USA, Inc.": "US",
    "Benaroya Research Institute ": "US",
    "Raive": "US",
    "feedzai": "PT",
    "Baylor College of Medicine": "US",
    "Kakao Brain": "KR",
    "University of Massachusetts at Lowell": "US",
    "Nutanix": "US",
    "Upwork Inc": "US",
    "Ethical AI Novelties": "US",
    "Citadel Securities": "US",
    "Invertible AI": "US",
    "inspur": "CN",
    "DENSO CORPORATION": "JP",
    "Biomap": "US",
    "Monash University": "AU",
    "MPG Ranch": "US",
    "Cainao Netwok": "CN",
    "Alipay": "CN",
    "Marquette University": "US",
    "Zebra Technologies": "US",
    "University of Oklahoma": "US",
    "Operant Biopharma": "US",
    "University of the District of Columbia": "US",
    "Telefonica Research": "ES",
    "UMass Chan Medical School": "US",
    "National Institute of Standards and Technology": "US",
    "The Hong Kong University of Science and Technology (Guangzhou)": "CN",
    "Brigham Young University": "US",
    "Apart Research": "US",
    "LiAuto": "CN",
    "Xiaohongshu": "CN",
    "Wesleyan University": "US",
    "Qatar Computing Research Institute": "QA",
    "China Nanhu Academy of Electronics and Information Technology": "CN",
    "sapeon": "KR",
    "Fujian(Quanzhou)Advanced Manufacturing Institute": "CN",
    "Nippon Telegraph and Telephone Corporation": "JP",
    "Bytedance Inc.": "CN",
    "Xiaomi ": "CN",
    "Cainiao Network": "CN",
    "Ericsson Canada": "CA",
    "Academic medical center at State University of New York at Stony Brook": "US",
    "Inner Mongolia University of Technology": "CN",
    "Medidata Solutions": "US",
    "Louisiana State University": "US",
    "Kuang-chi Institute of Advanced Technology": "TW",
    "XiaomiCamera": "CN",
    "TU Munich": "DE",
    "Xi'an Jiaotong University": "CN",
    "University of Louisiana at Lafayette": "US",
    "SenseTime Research": "CN",
    "Picsart": "US",
    "North South University": "BD",
    "CaiNiao Network": "CN",
    "Aleph Alpha": "DE",
    "Case Western Reserve University": "US",
    "VMware Research": "US",
    "HP Inc.": "US",
    "Wipro Technologies": "IN",
    "Harvey Mudd College": "US",
    "Capital One": "US",
    "Optum Labs": "US",
    "Xiaomi": "CN",
    "Institue for Advanced Study, Princeton": "US",
    "Universitat Rovira i Virgili": "ES",
    "Southern Methodist University, Southern Methodist University": "US",
    "Aleph-Alpha gmbh": "DE",
    "OxAI Safety Hub": "GB",
    "Shanghai Newtouch  Software  Co. Ltd": "CN",
    "Wormpex AI Research": "US",
    "FaunaPhotonics": "US",
    "Artificial Intelligence Research Institute": "US",
    "Central European University": "HU",
    "Woven Planet": "JP",
    "Machine Discovery": "US",
    "Northeastern University": "US",
    "tsinghua university": "CN",
    "STOCKTON UNIVERSITY": "US",
    "Tennessee State University": "US",
    "Washington University in St. Louis": "US",
    "University of Texas at Dallas": "US",
    "Enrich Biosystems": "US",
    "National Research University Higher School of Economics": "RU",
    "Peking Union Medical Collage": "CN",
    "KakaoBrain": "KR",
    "University of the Basque Country (UPV/EHU)": "ES",
    "Panasonic Corporation": "JP",
    "BIT": "CN",
    "pfizer": "US",
    "Institute of Physics, Henan Academy of Sciences": "CN",
    "NIO": "CN",
    "Universidad del País Vasco": "ES",
    "Sambanova Systems Inc.": "US",
    "Araya": "US",
    "Valve Corporation": "US",
    "Orcam": "IL",
    "Independant": "US",
    "Tilburg University": "NL",
    "KonanAI": "JP",
    "Collov Research": "US",
    "OneFlow Inc.": "US",
    "Oberlin College": "US",
    "Chongqing University of Posts and Telecommunications": "CN",
    "Iowa State University": "US",
    "Auburn University": "US",
    "University of Maine": "US",
    "Cellarity Inc": "US",
    "AntFin": "CN",
    "Cloudwise Research": "US",
    "Nanjing Tech University": "CN",
    "Mobileye": "IL",
    "NatInLab": "US",
    "Champalimaud Foundation": "PT",
    "Ecole Polytechnique": "FR",
    "Carlmont High School": "US",
    "University of Nevada, Reno, University of Nevada, Reno": "US",
    "BioMap": "US",
    "China Mobile research institute": "CN",
    "Picsart AI Research": "US",
    "Hikvision Research Institute": "CN",
    "Google DeepMind": "GB",
    "Ubisoft": "FR",
    "University of Texas Southwestern Medical Center": "US",
    "Sano - Centre for Personalised Computational Medicine": "US",
    "National Taiwan University": "TW",
    "MERCK & CO., INC.": "US",
    "Synerise S.A.": "PL",
    "Lynbrook High School": "US",
    "xiaohongshu": "CN",
    "Telefonica": "ES",
    "Xpeng Motors": "CN",
    "QCRI": "QA",
    "Dongguk University": "KR",
    "Howard University": "US",
    "Ant Group": "CN",
    "XSense.ai Inc.": "US",
    "United Automotive Electronic Systems": "CN",
    "National University of Singapore": "SG",
    "University of Louisiana at Lafeyette": "US",
    "Portland State University": "US",
    "Southeast University": "CN",
    "International School of Zug and Luzern": "CH",
    "China Mobile Research Institute": "CN",
    "University of Hawaii": "US",
    "Artificial Intelligence Research Institute (AIRI)": "US",
    "Huazhong University of Science and Technology": "CN",
    "Line Corp": "JP",
    "AI21 Labs": "IL",
    "AXA": "FR",
    "Operant BioPharma": "US",
    "Ximalaya Inc., China": "CN",
    "Georgia State University": "US",
    "University of Kentucky": "US",
    "Ximalaya Inc.": "CN",
    "LG Display": "KR",
    "Western Washington University": "US",
    "AIRI": "US",
    "IMT Atlantique": "FR",
    "Apziva": "US",
    "Hallmark University": "US",
    "TomTom": "NL",
    "Zebra technologies": "US",
    "Nostrum Biodiscovery": "US",
    "CJ Corporation": "KR",
    "Feedzai": "PT",
    "Siemens Corporate Research": "US",
    "SUNY Upstate Medical University": "US",
    "International Technological University": "US",
    "University of Guelph": "CA",
    "Independent": "US",
    "Evidation Health": "US",
    "Hippocratic AI": "US",
    "Illinois Institute of Technology": "US",
    "TianyiJiaotong Technology": "CN",
    "IMDEA Networks": "ES",
    "Yahoo": "US",
    "Zscaler": "US",
    "Nanhu Academy of Electronics and Information Technology": "CN",
    "MIT": "US",
    "Crofton House School": "CA",
    "Brac University": "BD",
    "Ocado Technology": "GB",
    "Li Auto": "CN",
    "Wise Plc": "GB",
    "Coral Gardeners": "US",
    "Aleph Alpha GmbH": "DE",
    "University of Pennsylvania": "US",
    "Center for Advanced Systems Understanding": "DE",
    "InfAI": "DE",
    "New York Institute of Technology": "US",
    "University of Vermont": "US",
    "Woods Hole Oceanographic Institution": "US",
    "Augment Computing": "US",
    "Southern Methodist University": "US",
    "Idemia Identity & Security": "FR",
    "UT Southwestern Medical Center": "US",
    "Kennesaw State University": "US",
    "Find & Order": "US",
    "Imperial College London": "GB",
    "Volkswagen Group Innovation": "DE",
    "Babban Gona": "NG",
    "United Automotive Electronic Systems Co., Ltd.": "CN",
    "Kakaobrain": "KR",
    "XiaoHongshu": "CN",
    "https://xinchenai.com/": "CN",
    "UAES": "CN",
    "Cerence GmbH": "DE",
    "Yahoo Research": "US",
    "Slb": "US",
    "Datakalab": "US",
    "Hebei University of Science & Technology": "CN",
    "Scaled Cognition": "US",
    "Emory University": "US",
    "shxmxn": "CN",
    "eBay Research": "US",
    "Wright State University": "US",
    "Cleveland State University": "US",
    "Hochschule München": "DE",
    "Innopolis University": "RU",
    "Jadavpur University": "IN",
    "Tongdun Technology Company Limited": "CN",
    "The Harker School": "US",
    "City of Hope": "US",
    "Indiana University": "US",
    "Wellesley College": "US",
    "University of Science and Technology of China": "CN",
    "DeepSeek AI": "US",
    "EQT": "SE",
    "Avatar Cognition": "US",
    "Splunk": "US",
    "Astroinformatics, HITS gGmbH, Heidelberg, Germany": "DE",
    "Inventec Corporation": "TW",
    "Champalimaud Centre for the Unknown": "PT",
    "NIST": "US",
    "FPT Software AI Center": "VN",
    "Intuit": "US",
    "Basque Center for Applied Mathematics": "ES",
    "University of Miami, University of Miami": "US",
    "University of California Berkeley": "US",
    "Ensem Therapeutics": "US",
    "state grid of china": "CN",
    "IMDEA Networks Institute": "ES",
    "Insitro": "US",
    "Tulane University": "US",
    "Austin Peay State University": "US",
    "Inventec Inc.": "TW",
    "HHMI Janelia Research Campus": "US",
    "NCSOFT": "KR",
    "Southern Illinois University-Carbondale": "US",
    "National Yang Ming Chiao Tung University": "TW",
    "Michigan Technological University": "US",
    "kakaobrain": "KR",
    "Hilabs Inc": "US",
    "University of Memphis": "US",
    "The Chinese University of Hong Kong, Shenzhen": "CN",
    "Texas Tech University": "US",
    "San Francisco State University": "US",
    "Spin-Quantum Co. LTD.": "CN",
    "Find&Order": "US",
    "NYU Langone": "US",
    "Carenostics": "US",
    "LG Electronics": "KR",
    "VW IECC": "DE",
    "Air Liquide": "FR",
    "LG Display Co., Ltd.": "KR",
    "Carnegie-Mellon University": "US",
    "Heidelberg Institute for Theoretical Studies": "DE",
    "SIG": "US",
    "Kakao Brain Corp.": "KR",
    "Saginaw Valley State University": "US",
    "VIVE STUDIOS": "TW",
    "Kakao Brain Corp": "KR",
    "University of Massachusetts, Boston": "US",
    "ItalAI S.R.L.": "IT",
    "Fordham University": "US",
    "NAVER WEBTOON": "KR",
    "University of Colorado at Denver": "US",
    "Worcester Polytechnic Institute": "US",
    "Indiana University, Bloomington": "US",
    "University of Massachusetts, Lowell": "US",
    "Zhihu": "CN",
    "Drexel University": "US",
    "AISIN SOFTWARE Co., Ltd.": "JP",
    "Mississippi State University": "US",
    "Pfizer": "US",
    "Bloomberg AI": "US",
    "Senslab Technology Co.,Ltd.": "CN",
    "Zhejiang Lab": "CN",
    "Academy of Military Science": "CN",
    "Information Sciences Institute": "US",
    "Ericsson": "SE",
    "University of Chinese Academy of Sciences": "CN",
    "Cactus Communications": "US",
    "Pendulum Systems": "US",
    "NEC": "JP",
    "Hyundai Motor Company": "KR",
    "Sambanova Systems, Inc": "US",
    "CMU, Carnegie Mellon University": "US",
    "Ca' Foscari University of Venice": "IT",
    "Cadence Design Systems": "US",
    "Leeroo AI": "GB",
    "University of Michigan Ann Arbor": "US",
    "Luis Villa Law": "US",
    "Two Sigma": "US",
    "POSCO HOLDINGS": "KR",
    "Valeo": "FR",
    "Sichuan University": "CN",
    "Cornell University": "US",
    "Moscow Institute of Physics and Technology": "RU",
    "xiaomi corporation": "CN",
    "Singapore Management University": "SG",
    "RTE France": "FR",
    "Harvard Business School": "US",
    "MiHoYo": "CN",
    "SambaNova Systems": "US",
    "Wake Forest Baptist Health": "US",
    "Trustees of Boston University": "US",
    "City University of New York": "US",
    "University of Texas Health Center at Houson": "US",
    "Moonshot Marketing": "IN",
    "Hong Kong University of Science and Technology (GuangZhou)": "CN",
    "Volkswagen AG": "DE",
    "UnSearch": "AU",
    "baichuan": "CN",
    "Federal Reserve Bank of Chicago": "US",
    "University of California-Berkeley": "US",
    "Verily": "US",
    "Upstream CFD GmbH": "DE",
    "University of New Haven": "US",
    "Georgia Tech Research Corporation": "US",
    "Deep Learning Indaba": "ZA",
    "XtalPi": "CN",
    "Sensetime  Research": "CN",
    "Panasonic Connect": "JP",
    "Baichuan Inc.": "CN",
    "Johnson and Johnson": "US",
    "Siemens Energy": "DE",
    "New College of Florida": "US",
    "University of Massachusetts Amherst": "US",
    "Department of Software Engineering, Shenzhen University": "CN",
    "Hewlett Packard Labs @ Hewlett Packard Enterprise": "US",
    "Deezer": "FR",
    "Uber": "US",
    "KC-ML2": "KR",
    "Universidad Politécnica de Catalunya": "ES",
    "Profluent Bio": "US",
    "Changan Automobile": "CN",
    "Pennsylvania State Univ University Park": "US",
    "Shenzhen University": "CN",
    "Lapis Labs": "US",
    "Bayer Ag": "DE",
    "MD Anderson Cancer Center": "US",
    "Johnson & Johnson": "US",
    "Antgroup": "CN",
    "National Renewable Energy Lab": "US",
    "Max Planck Institute for Security and Privacy": "DE",
    "Happy Elements": "CN",
    "KC Machine Learning Lab": "KR",
    "vivestudios": "KR",
    "MercadoLibre Inc.": "AR",
    "Michigan State University": "US",
    "University of Iowa": "US",
    "insitro": "US",
    "Harvard University": "US",
    "Upstream CFD": "DE",
    "Mila, UdeM": "CA",
    "Quantinuum Ltd.": "US",
    "lowRISC": "GB",
    "California Polytechnic State University, Pomona": "US",
    "BigHat Biosciences": "US",
    "DatologyAI": "US",
    "deepwisdom": "CN",
    "Elsevier": "NL",
    "Bose": "US",
    "Colorado School of Mines": "US",
    "Memorial Sloan Kettering Cancer Centre": "US",
    "CVTE Research Institute": "CN",
    "SenseAuto Research": "CN",
    "University of Texas Health Science Center at Houston": "US",
    "Huawei": "CN",
    "Stellarrover.Inc": "CN",
    "University of Houston": "US",
    "HippocraticAI": "US",
    "Thalesians Marine Ltd, the AI in shipping and logistics company": "GB",
    "MosaicML": "US",
    "Infinigence": "CN",
    "Crowdstrike Holdings Inc": "US",
    "Duke University": "US",
    "CUNY Queens College": "US",
    "NTT": "JP",
    "Hewlett Packard Enterprise": "US",
    "Boeing Research and Technology Software ": "US",
    "Dexcom, Inc.": "US",
    "Goethe University Frankfurt, Germany": "DE",
    "Air Force Research Laboratory, Information Directorate": "US",
    "United States Naval Academy": "US",
    "James Madison University": "US",
    "lastminute.com group": "GB",
    "constructor university": "DE",
    "Xiaohongshu Inc": "CN",
    "University College London": "GB",
    "Fidelity Investments": "US",
    "Rutgers University New Brunswick": "US",
    "Catalan Institute of Advanced Studies": "ES",
    "Fred Hutchinson Cancer Research Center": "US",
    "Flagship Pioneering": "US",
    "Albert Einstein College of Medicine, Inc.": "US",
    "China Mobile (Suzhou) Software Technology Company": "CN",
    "AppTek GmbH": "DE",
    "Shopee": "SG",
    "Indiana University Purdue University Indianapolis": "US",
    "Laboratory for Advanced Computing and  Intelligence Engineering": "US",
    "Earth Species Project": "US",
    "Indiana State University ": "US",
    "East China Normal University": "CN",
    "West Virginia University": "US",
    "RTE": "IE",
    "Analog Devices Inc": "US",
    "Writer": "US",
    "Baylor University": "US",
    "Xiamen BaishanCloud Technology Co., Ltd": "CN",
    "EchoX Technology Limited": "CN",
    "College of William and Mary": "US",
    "DSO National Laboratories": "SG",
    "Optum AI Labs": "US",
    "UC Berkeley": "US",
    "Max-Planck Institute for Security and Privacy": "DE",
    "Northern Arizona University": "US",
    "LG Corporation": "KR",
    "ellamind GmbH": "DE",
    "Northwestern Polytechnical University": "CN",
    "Microsoft Research Cambridge": "GB",
    "Genmab US Inc": "US",
    "National Open University": "IN",
    "Pinterest": "US",
    "University of Massachusetts Boston": "US",
    "InBalance": "ID",
    "Xiamen University": "CN",
    "Kinaxis inc.": "CA",
    "Predibase": "CA",
    "POSCO Holdings": "KR",
    "Leeroo": "GB",
    "Mashang Consumer Finance Co, Ltd": "CN",
    "ZOZO Research": "JP",
    "Hewlett Packard Labs": "US",
    "Verily Life Sciences": "US",
    "Panasonic Connect Co., Ltd.": "JP",
    "William Paterson University": "US",
    "USC/ISI": "US",
    "Infinigence-AI": "CN",
    "University of Alabama in Huntsville": "US",
    "POSCO holdings": "KR",
    "MoleculeMind": "US",
    "The Graduate Center, City University of New York": "US",
    "LINE Corporation": "JP",
    "Deezer Research": "FR",
    "CMRI": "IN",
    "University of North Texas": "US",
    "Quantinuum": "US",
    "CUNY Hunter College": "US",
    "Rakuten Institute of Technology": "JP",
    "Centrale Lille Alumni": "FR",
    "China Mobile Communications Company Limited Research Institute": "CN",
    "Mathematica Policy Research": "US",
    "Dimtech": "CN",
    "New Mexico State University": "US",
    "ILLUIN Technology": "FR",
    "SRI International": "US",
    "Florida Institute of Technology": "US",
    "University of California - Santa Cruz": "US",
    "eda": "UNK",
    "SaluteDevices": "US",
    "AIRI, Artificial Intelligence Research Institute": "RU",
    "Dartmouth College": "US",
    "Stellar Cyber, Inc.": "US",
    "Shanghai AI Laboratory": "CN",
    "NTT Human Informatics Laboratories, NTT Corporation": "JP",
    "Texas A&M University": "US",
    "Illuin Technology": "FR",
    "University of Michigan, Ann Arbor": "US",
    "University of Freiburg": "DE",
    "NYU": "US",
    "Renmin University of China": "CN",
    "Department of Computer Science, McGill University": "CA",
    "Baichuan AI": "CN",
    "Hamedan University of Technology": "IR",
    "Microsoft Research Asia": "CN",
    "Institute of Science Tokyo; Westlake University": "JP",
    "SGIT AI Lab": "CN",
    "Honor Device Co., Ltd": "CN",
    "ByteDance": "CN",
    "Shanghai Artificial Intelligence Laboratory": "CN",
    "Department of Advanced Manufacturing and Robotics, Peking University": "CN",
    "École Polytechnique Fédérale de Lausanne (EPFL)": "CH",
    "Redwood Research": "US",
    "Global Data Solutions Co., Ltd.": "CN",
    "The University of British Columbia": "CA",
    "Intuit AI Research": "US",
    "EPFL": "CH",
    "University of Amsterdam": "NL",
    "Department of Automation, Tsinghua University": "CN",
    "University Of Chicago Laboratory Schools": "US",
    "Anthropic": "US",
    "CyberAgent, Toyohashi University of Technology": "JP",
    "Mila": "CA",
    "Seed-Foundation-Model, ByteDance": "CN",
    "Modelyst": "US",
    "Microsoft Research": "US",
    "University of Bern": "CH",
    "Normal Computing": "US",
    "University of Kassel": "DE",
    "NTT Research": "JP",
    "MATS": "US",
    "NEC Labs Europe": "DE",
    "Zhejiang University": "CN",
    "University of California, LA": "US",
    "AWS AI Labs": "US",
    "DeepSeek-AI": "CN",
    "Institute of Science Tokyo": "JP",
    "Google": "US",
    "UCLA": "US",
    "Alibaba Group": "CN",
    "Eleos AI": "US",
    "Shanghai Meteorological Service": "CN",
    "State Key Laboratory of Virtual Reality Systems and Technology, Beihang University": "CN",
    "UK AISI": "GB",
    "TAL Education Group": "CN",
    "University of Copenhagen": "DK",
    "Uber Technologies Inc": "US",
    "University of Maryland": "US",
    "Abacus.AI": "US",
    "Individual Researcher": "UNK",
    "Department of Control Science and Engineering, Zhejiang University": "CN",
    "Department of Artificial Intelligence, Westlake University": "CN",
    "ServiceNow": "US",
    "University of Oxford": "GB",
    "LISMARS, Wuhan University": "CN",
    "iFLYTEK Research": "CN",
    "Mohamed bin Zayed University of Artificial Intelligence": "AE",
    "Nanbeige Lab, BOSS Zhipin": "CN",
    "ModelBest Inc.": "CN",
    "Tsinghua University": "CN",
    "Independent Researcher": "UNK",
    "Fudan University": "CN",
    "Moffett AI": "US",
    "Nissan Advanced Technology Center": "JP",
    "Beijing University of Posts and Telecommunications": "CN",
    "Nomic AI": "US",
    "Amazon Web Services": "US",
    "CMU": "US",
    "Sony AI": "JP",
    "Cornell": "US",
    "Private Consultant": "UNK",
    "OpenAI": "US",
    "CCSE, Beihang University": "CN",
    "Zhejiang University of Technology": "CN",
    "Anhui Polytechnic University": "CN",
    "Intellifusion Inc.": "CN",
    "Nanjing University": "CN",
    "Haize Labs": "CN",
    "KRAFTON": "KR",
    "McGill, Mila": "CA",
    "Hangzhou Dianzi University": "CN",
    "University of California, Santa Barbara": "US",
    "Weizmann Institute of Science": "IL",
    "Kuaishou Technology": "CN",
    "Kumo.AI": "US",
    "UMass Amherst": "US",
    "UC Davis": "US",
    "ItalAI, Procederai": "IT",
    "Georgia Institute of Technology": "US",
    "Accenture Cyber Labs": "IE",
    "State Key Laboratory of General Artificial Intelligence, BIGAI": "CN",
    "Coventry University": "GB",
    "DeepWisdom": "CN",
    "Zyphra": "US",
    "Intelligent Game and Decision Laboratory": "CN",
    "ByteDance Research": "CN",
    "Gray Swan AI": "US",
    "Tencent": "CN",
    "Zhipu AI": "CN",
    "MIT-IBM Watson AI Lab": "US",
    "IBM Research": "US",
    "Intel": "US",
    "YerevaNN research lab": "AM",
    "Department of Neuroscience, Baylor College of Medicine": "US",
    "Meta": "US",
    "Multimodal Art Projection Research Community, 42077.AI": "UNK",
    "The University of Texas at Austin": "US",
    "Indo Ocean Project": "ID",
    "Broad Institute of MIT and Harvard": "US",
    "Unity Technologies": "US",
    "SJTU": "CN",
    "Thomas Jefferson University": "US",
    "HCMUT": "VN",
    "T-Tech": "IN",
    "ETH Zurich": "CH",
    "Vaneval": "CN",
    "Tel Aviv University": "IL",
    "Huawei Noah’s Ark Lab": "CN",
    "Intel Labs": "US",
    "Dian Diagnostics Group Co.": "CN",
    "University of Padova": "IT",
    "JD.com": "CN",
    "Mila, McGill University": "CA",
    "Noah’s Ark Lab": "CN",
    "AlpsenTek": "CN",
    "ByteDance Inc.": "CN",
    "State Key Lab of CAD&CG, Zhejiang University": "CN",
    "Deakin University": "AU",
    "The School of Computer Science and Engineering, Sun Yat-sen University": "CN",
    "Meta Platforms, Inc.": "US",
    "LibAI Lab": "US",
    "Alibaba Group, Institute for Intelligent Computing (Tongyi Lab)": "CN",
    "Toyota North America": "US",
    "Sungkyunkwan University": "KR",
    "University of Toronto, Meta FAIR": "CA",
    "Amazon": "US",
    "Chuanglin Tech": "CN",
    "Huawei Technologies Co., Ltd": "CN",
    "The Hong Kong Polytechnic University": "HK",
    "I2R, A*STAR": "SG",
    "Helmholtz Munich, Technical University of Munich": "DE",
    "Sun Yat-Sen Memorial Hospital, Sun Yat-Sen University": "CN",
    "Criteo AI Lab": "FR",
    "Tongji University": "CN",
    "Meta GenAI": "US",
    "The Chinese University of Hong Kong": "HK",
    "Guangzhou Meteorological Observatory": "CN",
    "Technische Universität Berlin": "DE",
    "Simular Research": "NO",
    "University of California, San Diego": "US",
    "TEX AI, Transsion": "CN",
    "UC San Diego": "US",
    "Multimodal Art Projection Research Community, University of Illinois at Urbana-Champaign": "US",
    "Tencent Hunyuan": "CN",
    "North China University of Technology": "CN",
    "Nanyang Technological University": "SG",
    "Anthropic, UCL": "GB",
    "Graphcore": "GB",
    "AI Sweden": "SE",
    "Cohere For AI": "CA",
    "Boeing AI": "US",
    "Microsoft Research AI4Science": "US",
    "Databricks": "US",
    "Shanghai Qi Zhi Institute": "CN",
    "Jagiellonian University": "PL",
    "M-A-P": "US",
    "Institute of Artificial Intelligence, Beihang University": "CN",
    "DreamTech": "CN",
    "Beijing StoneWise Technology Co Ltd": "CN",
    "Bilibili Inc": "CN",
    "Dalian University of Technology": "CN",
    "UMN": "US",
    "Shanghai Academy of Artificial Intelligence for Science": "CN",
    "Tsinghua SIGS": "CN",
    "University of Piraeus": "GR",
    "SenseTime": "HK",
    "Institute of Automation, Chinese Academy of Sciences": "CN",
    "Quris AI": "IL",
    "Du Xiaoman Financial": "CN",
    "School of Computer Science and Engineering, Sun Yat-sen University": "CN",
    "NAVER Cloud": "KR",
    "Samsung Research": "KR",
    "Airbus": "FR",
    "Allen Institute for Neural Dynamics": "US",
    "BioMap Research": "UNK",
    "Microsoft Research AI for Science": "US",
    "SI-TECH Information Technology": "UNK",
    "Cohere": "CA",
    "KDDI Research": "JP",
    "Hugging Face": "US",
    "Huawei HiSilicon": "CN",
    "CREST, ENSAE": "FR",
    "Meituan Inc.": "CN",
    "Technion – Israel Institute of Technology": "IL",
    "CREST, ENSAE, Criteo AI LAB, Fairplay joint team": "FR",
    "Intelligent Science and Technology Academy of CASIC": "CN",
    "FairPlay Team, CREST, ENSAE - Criteo AI Lab": "FR",
    "Institute for Acoustics and Dynamics, Technische Universität Braunschweig": "DE",
    "Singapore University of Social Sciences": "SG",
    "Independent researcher formerly at MIT": "UNK",
    "Tencent Youtu Lab": "CN",
    "German Research Center for Artificial Intelligence (DFKI)": "DE",
    "Simon Fraser University": "CA",
    "Google Research": "US",
    "Five AI Ltd.": "GB",
    "Harmonic Discovery": "US",
    "Unaffiliated": "UNK",
    "Beihang University": "CN",
    "Ampere Software Technology": "FR",
    "Janelia Research Campus, Howard Hughes Medical Institute": "US",
    "China Mobile Shanghai ICT Co., Ltd": "CN",
    "New York University Shanghai": "CN",
    "Department of Electrical and Computer Engineering, University of Florida": "US",
    "North Carolina State University": "US",
    "Ghent University, FlandersMake–MIRO": "BE",
    "University of British Columbia": "CA",
    "GE Healthcare": "US",
    "School of EECS, Peking University": "CN",
    "Taobao & Tmall Group of Alibaba": "CN",
    "Kunming University of Science and Technology": "CN",
    "China Academic of Electronics and Information Technology": "CN",
    "Shanghai Qizhi Institute": "CN",
    "Mozilla": "US",
    "CREST, ENSAE, Criteo AI LAB": "FR",
    "Shenzhen International Center for Industrial and Applied Mathematics; Shenzhen Research Institute of Big Data": "CN",
    "School of Public Administration, Xiangtan University": "CN",
    "Novonesis": "DK",
    "Beijing Institute of Technology": "CN",
    "Institute of Systems Engineering, Academy of Military Sciences, PLA": "CN",
    "Microsoft": "US",
    "Createlink Technology": "CN",
    "Faculty of Data and Decision Sciences, Technion": "IL",
    "Italian Competition Authority": "IT",
    "New York University": "US",
    "Equall": "US",
    "SODA Team, Inria Saclay": "FR",
    "Tencent PCG": "CN",
    "State Key Laboratory of Cognitive Intelligence": "CN",
    "TU Berlin, University of Potsdam, University of Birmingham": "DE",
    "Meta FAIR": "US",
    "Broad Institute of MIT and Harvard, Cancer Program, Eric and Wendy Schmidt Center": "US",
    "IHU Liryc": "FR",
    "Stanford": "US",
    "InstaDeep": "GB",
    "Atinary Technologies": "FR",
    "PhiGent Robotics": "CN",
    "Exp. Psychology, Oxford": "GB",
    "Peking University": "CN",
    "Sichuan University Pittsburgh Institute, Sichuan University": "CN",
    "Georgia Tech": "US",
    "Autonomous Driving Division, NIO": "CN",
    "Paris Elite Institute of Technology, Shanghai Jiao Tong University": "FR",
    "Ochanomizu Women's University": "JP",
    "Wellcome Sanger Institute": "GB",
    "Hitachi, Ltd.": "JP",
    "Shanghai AI Lab": "CN",
    "The Hebrew University of Jerusalem": "IL",
    "FedML, Inc.": "US",
    "Université Paris-Sorbonne (Paris IV)": "FR",
    "Department of Computer Science, University of Wisconsin, Madison": "US",
    "Tinkoff": "RU",
    "École de technologie supérieure": "CA",
    "Shenzhen Institutes of Advanced Technology, Chinese Academy of Sciences, Chinese Academy of Sciences": "CN",
    "University of Tübingen": "DE",
    "Bosch Center for Artificial intelligence": "DE",
    "EMPA Swiss Federal Laboratories for Materials Science and Technology": "CH",
    "Bosch Center for Artificial Intelligence": "DE",
    "Xiangtan University": "CN",
    "Research, Microsoft": "US",
    "Washington University, St. Louis": "US",
    "SINTEF": "NO",
    "UKRI Turing AI Fellow": "GB",
    "Eindhoven University of Technology": "NL",
    "School of Science and Engineering, The Chinese University of Hong Kong, Shenzhen": "CN",
    "US food and drug administration": "US",
    "Bosch research": "DE",
    "Northumbria University": "GB",
    "Sony Corporation": "JP",
    "OMRON SINIC X Corporation": "JP",
    "Allen Institute + University of Washington": "US",
    "Norwegian Institute for Air Research": "NO",
    "School of Engineering and Applied Sciences, Harvard University": "US",
    "Washington University, Saint Louis": "US",
    "Institute of Science and Technology": "UNK",
    "University of Amsterdam, University of Amsterdam": "NL",
    "Tsinghua-Berkeley Shenzhen Institute, Tsinghua University": "CN",
    "POSTECH": "KR",
    "Ecole Normale Superieure": "FR",
    "Yazd University": "IR",
    "CEA": "FR",
    "Chongqing Technology and Business University": "CN",
    "Beijing University Of Technology": "CN",
    "Universität Hannover": "DE",
    "IBM Thomas J. Watson Research Center": "US",
    "Indian Institute of Science, Bangalore": "IN",
    "Zhipu.AI": "CN",
    "Helmholtz Munich": "DE",
    "Microsoft Research NYC": "US",
    "University of Wisconsin - Madison": "US",
    "NanJing University": "CN",
    "Université de Toulouse, LAAS CNRS": "FR",
    "Technische Universität Graz": "AT",
    "Texas A&M University at Qatar": "QA",
    "Université Paris-Saclay": "FR",
    "Meta Fundamental AI Research": "US",
    "Argonne National Laboratory": "US",
    "University of Electro-Communications, Tokyo Institute of Technology": "JP",
    "Hamburg University Of Applied Sciences": "DE",
    "AOI": "UNK",
    "Université de Montréal": "CA",
    "University of South Florida": "US",
    "Inria": "FR",
    "Göteborg University": "SE",
    "Beijing University of Chemical Technology": "CN",
    "Northwest Polytechnical University Xi'an": "CN",
    "University of Surrey": "GB",
    "National Applied Research Laboratories": "TW",
    "IHPC": "SG",
    "Mines ParisTech": "FR",
    "University of Minnesota - Twin Cities": "US",
    "Peng Cheng Laboratory, Shenzhen, China": "CN",
    "Beijing Normal University - Hong Kong Baptist University United International College": "HK",
    "Huawei Technologies Ltd.": "CN",
    "Bar-Ilan University": "IL",
    "Indian Institute of Technology Kharagpur, Dhirubhai Ambani Institute Of Information and Communication Technology": "IN",
    "Kangwon National University": "KR",
    "Meta AI": "US",
    "Department of Information Engineering, PLA Army Academy of Artillery and Air Defense": "CN",
    "NORTHWEST A&F UNIVERSITY": "CN",
    "Institute of Information Engineering": "UNK",
    "Indian Institute of Technology, Madras": "IN",
    "Meituan Group": "CN",
    "Telecom Paristech": "FR",
    "University of California, Berkeley": "US",
    "NORCE Norwegian Research Centre": "NO",
    "Pasqal": "FR",
    "University of Greenwich": "GB",
    "Institut National des Sciences Appliquées de Lyon": "FR",
    "Department of Computer Science, University of Massachusetts at Lowell": "US",
    "Universitat de les Illes Balears": "ES",
    "Kookmin University": "KR",
    "HEC Paris": "FR",
    ", Virginia Polytechnic Institute and State University": "US",
    "HEC Montreal": "CA",
    "University of Minnesota, Minneapolis": "US",
    "IT University of Copenhagen": "DK",
    "South University of Science and Technology of China": "CN",
    "University of Texas at Arlington": "US",
    "Ecole Normale Supérieure, Ecole Normale Supérieure de Paris": "FR",
    "Beijing Language and Culture University": "CN",
    "Cleanlab": "US",
    "Flanders Make": "BE",
    "Amaros AI": "UNK",
    "AppliedAI Institute for Europe": "UNK",
    "Technion - Israel Institute of Technology, Technion": "IL",
    "Amazon Development Center Germany": "DE",
    "University of Catania": "IT",
    "Technion, Technion": "IL",
    "Centre For Frontier AI Research, A*STAR. Singapore": "SG",
    "University of Massachusetts, Amherst": "US",
    "Adobe Systems": "US",
    "Westfälische Wilhelms-Universität Münster": "DE",
    "UC Santa Barbara": "US",
    "Shenzhen International Graduate School, Tsinghua University": "CN",
    "Indian Institute of Science": "IN",
    "IBM India Ltd": "IN",
    "Apple": "US",
    "Huawei Technologies Ltd. (Pairs Resaerch Center)": "CN",
    "Max Planck Institute for Intelligent Systems, Max-Planck Institute": "DE",
    "University of Western Ontario": "CA",
    "State University of New York at Buffalo": "US",
    "Kyungpook National University": "KR",
    "University of Alicante": "ES",
    "Universite Laval, Laval university": "CA",
    "Hokkaido University": "JP",
    "University of Georgia": "US",
    "Qualcomm Inc": "US",
    "Victoria University of Wellington": "NZ",
    "University of California, Los Angeles": "US",
    "Ariel University": "IL",
    "University of Birmingham": "GB",
    "Chinese Academy of Sciences": "CN",
    "Idiap Research Institute": "CH",
    "Washington State University at Pullman": "US",
    "PowerTensors Technology": "UNK",
    "Electronic Engineering, Tsinghua University, Tsinghua University": "CN",
    "University of Missouri - Columbia": "US",
    "Seoul National University": "KR",
    "City University of Hong Kong": "HK",
    "Fondazione Bruno Kessler": "IT",
    "State University of New York, Stony Brook": "US",
    "Wuhan University of Technology": "CN",
    "KAUST": "SA",
    "Department of Computer Science, Cornell University": "US",
    "SERI MATS": "UNK",
    "Chinese University of HongKong": "HK",
    "Chongqing University of Post and Telecommunications": "CN",
    "Mizuho–DL Financial Technology": "JP",
    "Khalifa University of Science, Technology and Research": "AE",
    "Graduate School of Mathematics, Nagoya University": "JP",
    "STATE GRID ZHEJIANG ELECTRIC POWER COMPANY": "CN",
    "Meta Inc.": "US",
    "SIAnalytics": "UNK",
    "MPI for Biological Intelligence": "DE",
    "Lund University": "SE",
    "Deepmind": "GB",
    "Cerebras Systems, Inc": "US",
    "Autodesk": "US",
    "The Chinese University of Hong": "HK",
    "Universität Stuttgart": "DE",
    "Sharif University of Technology, Sharif University of Technology": "IR",
    "Konyang University": "KR",
    "Jiangxi Normal University": "CN",
    "Pontificia Universidad Católica": "CL",
    "Indian Institute of Technology, Madras, Dhirubhai Ambani Institute Of Information and Communication Technology": "IN",
    "Indian Institute of Technology Goa": "IN",
    "IIT (BHU), Varanasi": "IN",
    "Lenovo": "CN",
    "Xiamen Univeristy Malaysia": "MY",
    "Sensetime": "CN",
    "NTT Corporation": "JP",
    "Oculus": "US",
    "BorealisAI": "CA",
    "Universidade Federal do Rio de Janeiro": "BR",
    "The University of Waikato": "NZ",
    "UCLouvain": "BE",
    "Jagiellonian University Cracow": "PL",
    "University of Agder": "NO",
    "Fundação Getulio Vargas": "BR",
    "University of Central Punjab, Lahore": "PK",
    "Montreal Institute for Learning Algorithms, University of Montreal, Université de Montréal": "CA",
    "Institute of Semiconductors, Chinese Academy of Sciences": "CN",
    "University of Montreal": "CA",
    "Megvii Technology Inc.": "CN",
    "German Heart Center of the Charité": "DE",
    "TU Darmstadt": "DE",
    "lg ai research": "KR",
    "Mila - Québec AI Institute; Université de Montréal": "CA",
    "University of Sydney": "AU",
    "Research, Facebook": "US",
    "IQVIA": "US",
    "Department of Computer Science, University of North Carolina, Chapel Hill": "US",
    "Computer Network Information Center, Chinese Academy of Sciences": "CN",
    "China University of Geosciences Wuhan": "CN",
    "Harbin Institute of Technology (Shenzhen)": "CN",
    "The Institute of Statistical Mathematics, Japan": "JP",
    "Tianjin University of Technology": "CN",
    "university  of tianjin of china, Tianjin University": "CN",
    "Institute of Computing Technology, Chinese Academy of Sciences, China": "CN",
    "QualComm": "US",
    "Guangdong Institute of Intelligence Science and Technology": "CN",
    "Department of Physiology, ünivelsitat Bern": "CH",
    "IIT Bombay": "IN",
    "Mila, Quebec AI institute": "CA",
    ", Institute of automation, Chinese academy of science": "CN",
    "Istituto Italiano di Tecnologia": "IT",
    "Sambanova Systems": "US",
    "University of Bologna": "IT",
    "RWTH Aachen University": "DE",
    "KTH Royal Institute of Technology, Stockholm, Sweden": "SE",
    "Université Jean Monnet, Inria": "FR",
    "Central Conservatory of Music": "CN",
    "School of Computer Science and  Engineering, Nanyang Technological University": "SG",
    "Apollo Research": "UNK",
    "Peng Cheng Laboratory": "CN",
    "ISIR, UMR 7222": "FR",
    "Neural Concept": "UNK",
    "Universidade Federal de São Carlos": "BR",
    "King Mongkut's University of Technology Thonburi": "TH",
    "University of South Carolina": "US",
    "Queen Mary University London": "GB",
    "Universidad de Sevilla": "ES",
    "Boston University, Boston University": "US",
    "Computer Science 2, Technion - Israel Institute of Technology": "IL",
    "The University of Adelaide": "AU",
    "University of Hong Kong": "HK",
    "Simons Foundation": "US",
    "UCLouvain ICTEAM": "BE",
    "SCHUFA": "DE",
    "Prescient Design, Genentech": "US",
    "King's College London, University of London": "GB",
    "Mitsubishi Electric Information Technology R&D Center": "JP",
    "Royal Melbourne Institute of Technology": "AU",
    "Universitat de València": "ES",
    "Technische Universität Darmstadt": "DE",
    "Chongqing Jiaotong Universiity": "CN",
    "The University of Texas, Austin": "US",
    "Bar Ilan University": "IL",
    "University of Zurich": "CH",
    "Ecole Nationale Supérieure de Techniques Avancées": "FR",
    "University of Connecticut": "US",
    "Welcome Sanger": "GB",
    "CUHK(SZ)": "CN",
    "Universität Siegen": "DE",
    "University of Wrocław": "PL",
    "Ruprecht-Karls-Universität Heidelberg": "DE",
    "The University of Tokyo, Tokyo Institute of Technology": "JP",
    "Graduate Institute of Communication Engineering, National Taiwan University": "TW",
    "Beijing Normal University Hong Kong Baptist University United International College": "HK",
    "Hasso Plattner Institute": "DE",
    "Université Claude Bernard (Lyon I)": "FR",
    "Department of Computer Science, University of Washington": "US",
    "Technical University of Poznan": "PL",
    "University of Cambridge": "GB",
    "The University of North Carolina at Chapel Hill, USA": "US",
    "The University of Warwick": "GB",
    "University of Chicago": "US",
    "IGSNRR, Chinese Academy of Sciences, Beijing, China": "CN",
    "Bayerische Julius-Maximilians-Universität Würzburg": "DE",
    "University of Notre Dame": "US",
    "University of Warsaw": "PL",
    "Facebook": "US",
    "Graduate School at Shenzhen, Tsinghua University": "CN",
    "ShanghaiTech University": "CN",
    "University of Arizona": "US",
    "Xidian University": "CN",
    "Bytedance Inc": "CN",
    "Honda Research Institute Europe": "DE",
    "Chongqing University of Technology": "CN",
    "Lund University / Lund Institute of Technology": "SE",
    "Flinders University of South Australia": "AU",
    "University of Virginia": "US",
    "Meiji University": "JP",
    "Seoul National University of Science and Technology": "KR",
    "Osaka University": "JP",
    "CyberAgent, Inc.": "JP",
    "Academy of Mathematics and Systems Science, Chinese Academy of Sciences, Chinese Academy of Sciences": "CN",
    "Johannes Kepler University Linz": "AT",
    "Department of Mechanical and Industrial Engineering, University of Toronto, Toronto University": "CA",
    "Shanghai Normal University": "CN",
    "Tata Consultancy Services Limited, India": "IN",
    "NAVER": "KR",
    "Dyno Therapeutics": "US",
    "Stevens Institute of Technology": "US",
    "Harvard University, Harvard University": "US",
    "Tokyo University of Science": "JP",
    "Indian Institute of Technology Kanpur": "IN",
    "Stockholm University": "SE",
    "Rutherford Appleton Laboratory, Science and Technology Facilities Council": "GB",
    "Sony Computer Science Laboratories Inc (Tokyo)": "JP",
    "Max-Planck Institute": "DE",
    "New Jersey Institute of Technology": "US",
    "University of Melbourne": "AU",
    "Université de Cergy-Pontoise": "FR",
    "University of California, Merced": "US",
    "Samsung": "KR",
    "Isfahan University of Technology, University of Tehran": "IR",
    "Julius-Maximilians-Universität Würzburg": "DE",
    "Indian Institute of Technology, Hyderabad, Dhirubhai Ambani Institute Of Information and Communication Technology": "IN",
    "NTT, The University of Tokyo": "JP",
    "Saarland Informatics Campus, Max-Planck Institute": "DE",
    "NVIDIA": "US",
    "NEC-Labs": "JP",
    "Indian Statistical Institute, Kolkata": "IN",
    "Copenhagen University": "DK",
    "VUNO Inc.": "KR",
    "University of South Australia, Australia": "AU",
    "Amazon AWS": "US",
    "Institute of Artificial Intelligence": "CN",
    "Universität Freiburg": "DE",
    "McGill University": "CA",
    "Didi Research": "CN",
    "Helmholtz Zentrum München": "DE",
    "Paul G. Allen School of Computer Science & Engineering, University of Washington": "US",
    "University of Warwick": "GB",
    "Ruhr-Universität Bochum": "DE",
    "Lebanese University": "LB",
    "Queen's University": "CA",
    "University of Nebraska, Lincoln": "US",
    "ChinaTelecom": "CN",
    "University Politehnica of Bucharest": "RO",
    "SIGS, Tsinghua University": "CN",
    "University of Maryland, College Park": "US",
    "University of Illinois, Urbana Champaign": "US",
    "YerevaNN Research Lab": "AM",
    "Texas A&M University - Commerce": "US",
    "Lanzhou University": "CN",
    "China Unicom Research Institute": "CN",
    "EPFL - EPF Lausanne": "CH",
    "International Business Machines": "US",
    "University of Liège": "BE",
    "Computer Science Department, Carnegie Mellon University": "US",
    "Institute of Acoustics, Chinese Academy of Sciences": "CN",
    "Department of Electrical Engineering, KU Leuven, Belgium, KU Leuven": "BE",
    "Chalmers University of Technology": "SE",
    "American University of Beirut": "LB",
    "Toyota Research Institute": "US",
    "Koç University": "TR",
    "Dalian Martime University": "CN",
    "Technische Universität Hamburg": "DE",
    "Insitute for Basic Science": "KR",
    "J.P. Morgan Chase": "US",
    "Malmo University": "SE",
    "Polytechnic Institute of Milan": "IT",
    "Universität Paderborn": "DE",
    "Ajou University": "KR",
    "meta": "US",
    "Parameter Lab": "UNK",
    "Helmholtz-Zentrum Dresden-Rossendorf": "DE",
    "Yandex": "RU",
    "Instituto Tecnológico Autonómo de México": "MX",
    "Institute of Automation Chinese Academy of Sciences": "CN",
    "Cardiff University": "GB",
    "Karlsruher Institut für Technologie": "DE",
    "Department of Computer Science and Engineering, The Hong Kong University of Science and Technology": "HK",
    "NAVER CLOUD": "KR",
    "Krafton Inc.": "KR",
    "University of California Berkeley, USA": "US",
    "SalesForce.com": "US",
    "Institut d'Astrophysique de Paris": "FR",
    "Université d'Aix-Marseille": "FR",
    "Université de Nice-Sophia Antipolis": "FR",
    "International Institute of Information Technology, Hyderabad": "IN",
    "Institute for Interdisciplinary Information Sciences, Tsinghua University": "CN",
    "Medizinische Universität Wien": "AT",
    "KTH Royal Institute of Technology": "SE",
    "James Cook University of North Queensland": "AU",
    "Eötvös Lorand University": "HU",
    "Beijing Academy of Artificial Intelligence": "CN",
    "University of Portsmouth": "GB",
    "Cohere AI": "US",
    "Institute for AI in Medicine IKIM": "UNK",
    "National school of Tunis": "TN",
    "shanghai ai laboratory": "CN",
    "Yale University": "US",
    "Institute of Automation, Chinese Academy of Science": "CN",
    ", Tufts University": "US",
    "VantAI": "UNK",
    "Bytedance": "CN",
    "StabilityAI": "GB",
    "Waymo": "US",
    "School of Computer Science, Tel Aviv University": "IL",
    "Pacific Northwest National Lab": "US",
    "Microsoft Research, India": "IN",
    "Université Claude Bernard Lyon1 - LAGEPP": "FR",
    "Fraunhofer Institut für Kognitive Systeme IKS": "DE",
    "Sourthern University of Science and Technology": "CN",
    "Salesforce Research": "US",
    "Centre for Artificial Intelligence and Robotics, Hong Kong Institute of Science & Innovation, Chinese Academy of Sciences": "HK",
    "ISCTE - Instituto Universitário de Lisboa": "PT",
    "ByteDance, AI Lab": "CN",
    "UiT The Arctic University of Norway": "NO",
    "Guangxi Key Laboratory of Trusted Software": "CN",
    "Department of Computer Science, Yale University": "US",
    "Samsung SDS": "KR",
    "Together AI": "UNK",
    "Potsdam Institute for Climate Impact Research": "DE",
    "Center for AI Safety": "US",
    "Ulsan National Institute of Science and Technology": "KR",
    "Beijing Teleinfo Technology Company Limited": "CN",
    "Max-Planck-Institute for Intelligent Systems, Max-Planck Institute": "DE",
    "BITS Pilani, Birla Institute of Technology and Science": "IN",
    "The Skolkovo Institute of Science and Technology": "RU",
    "PASQAL": "FR",
    "AI Safety Institute": "UNK",
    "Aix Marseille Univ": "FR",
    ", University of California, Los Angeles": "US",
    "Duke Kunshan University": "CN",
    "Skolkovo Institute of Science and Technology": "RU",
    "Huawei Noah' Ark Lab": "CN",
    "Seoul City University": "KR",
    "Honda Research Institute": "JP",
    "Vector Institute": "CA",
    "Department of Computer Science, Princeton University": "US",
    "Weill Cornell Medicine, Cornell University": "US",
    "Technische Universität Wien": "AT",
    "Polygeist": "UNK",
    "University of California, Santa Cruz": "US",
    "BRAC University": "BD",
    "Universidad de Valladolid": "ES",
    "McGill University, McGill University": "CA",
    "Hebrew University, Hebrew University of Jerusalem": "IL",
    "University of Texas, Arlington": "US",
    "NYU Grossman School of Medicine": "US",
    "Institut National des Sciences Appliquées de Toulouse": "FR",
    "Department of Computer Science and Engineering, Hong Kong University of Science and Technology": "HK",
    "Ludwig-Maximilians-Universität München": "DE",
    "Pacific Northwest National Laboratory": "US",
    "St. Petersburg Department of Steklov Mathematical Institute": "RU",
    "Henan Academy of Sciences": "CN",
    "Los Alamos National Laboratory": "US",
    "Cyprus University of Technology": "CY",
    "Southwest Jiaotong University": "CN",
    "Bosch Center for Artificial Inteligence": "DE",
    "Bloorview Research Institute, Holland Bloorview Kids Rehabilitation Hospital": "CA",
    "Samsung Advanced Institute of Technology": "KR",
    "Samsung AI Center": "KR",
    "Genentech Inc.": "US",
    "Institute of High Performance Computing, Singapore, A*STAR": "SG",
    "Medical University of Vienna": "AT",
    "Ruhr-Universtät Bochum": "DE",
    "University of Ostrava": "CZ",
    "University of Winnipeg": "CA",
    "The Hong Kong University of Science and Technology": "HK",
    "NEC Labs America": "US",
    "Tokyo Institute of Technology, Tokyo Institute of Technology": "JP",
    "Indian Institute of Technology, Delhi": "IN",
    "Ecole Normale Supérieure de Paris": "FR",
    "Tokyo University of Agriculture and Technology, Tokyo Institute of Technology": "JP",
    "Pyramidal, Inc": "US",
    "Department of Computer Science": "UNK",
    "Lawrence Livermore National Labs": "US",
    "INF (Shanghai) Technology Co., LTD": "CN",
    "Xi'an Jiaotong University, Tsinghua University": "CN",
    "George Mason University": "US",
    "Zhejiang Sci-Tech University": "CN",
    "Karolinska Institute Stockholm": "SE",
    "Lawrence Livermore National Laboratory": "US",
    "Five AI": "GB",
    "University of Texas, Dallas": "US",
    "Department of Computer Science, National Tsing Hua University, National Tsinghua University": "TW",
    "Seoul National University, Seoul National University": "KR",
    "University of Washington, Seattle": "US",
    "Nanjing university": "CN",
    "Charles University, Prague": "CZ",
    "Skywork AI PTE. LTD.": "SG",
    "National University Hospital": "SG",
    "northeastern university": "US",
    "University of Mons": "BE",
    "Sony Research India Pvt. Ltd.": "IN",
    "inner mongolia university": "CN",
    "Daegu Gyeongbuk Institute of Science and Technology": "KR",
    "Virginia Polytechnic Institute and State University": "US",
    "Ariel University Center of Samaria": "IL",
    "Shanghai Business School": "CN",
    "NII, the Graduate University for Advanced Studies": "JP",
    "Baidu Research": "CN",
    "University of Eastern Finland": "FI",
    "Bosch": "DE",
    "meituan": "CN",
    "University of Siegen": "DE",
    "Waabi": "CA",
    "University of Bath": "GB",
    "China Pacific Insurance (Group) Co., Ltd.": "CN",
    "Microsoft Research AI": "US",
    "Amsterdam UMC": "NL",
    "Sorbonne University": "FR",
    "EPFL - Lausanne": "CH",
    "MediaTek USA Inc": "US",
    ", Chinese Academy of Sciences": "CN",
    "Testworks Inc.": "US",
    "University of Haifa": "IL",
    "Skoltech": "RU",
    "Institute for Interdisciplinary Information Sciences, Tsinghua University, Tsinghua University": "CN",
    "Northwest Polytechnical University": "CN",
    "Salesforce AI Research": "US",
    "National University of Defense Technology": "CN",
    "Universität Bern": "CH",
    "Fujitsu Research and Development Center Co., Ltm.": "JP",
    "Fuzhou University": "CN",
    "Sea AI Lab": "CN",
    "Complex Carbohydrate Research Center": "US",
    "The Kim Jaechul Graduate School of AI at Korea Advanced Institute of Science and Technology": "KR",
    "Suzhou University": "CN",
    "University of Massachusetts at Amherst": "US",
    "Data Lab, Volkswagen Group": "DE",
    "Hebrew University of Jerusalem, Israel": "IL",
    "NAVER CLOVA": "KR",
    "Ecole Polytechnique, France": "FR",
    "Hunan University": "CN",
    "Department of Computer Science, University of Massachusetts, Amherst": "US",
    "DISI - University of Bologna": "IT",
    "Institute of Engineering, Pulchowk Campus": "NP",
    "Université de Limoges": "FR",
    "University of Münster": "DE",
    "Max Planck Institute for Biological Cybernetics": "DE",
    "Sharif University of Technology": "IR",
    "Qiyuan laboratory": "CN",
    "Hohai University": "CN",
    "SK Telecom": "KR",
    "Universidade Federal de Pernambuco, Universidade Federal de Pernambuco": "BR",
    "Sber AI": "RU",
    "IRT SystemX": "FR",
    "Guilin University of Electronic Technology": "CN",
    "University of Witwatersrand": "ZA",
    "Academy of Mathematics and Systems Science, Chinese Academy of Sciences": "CN",
    "Facebook AI Research": "US",
    "Beijing University of Aeronautics and Astronautics": "CN",
    "SenseTime Co.": "CN",
    "Amazon AI Research Lab": "US",
    "Mila- Quebec AI Institute": "CA",
    "Vrije Universiteit Brussel": "BE",
    "Meta Platforms, Inc": "US",
    "Tencent data platform": "CN",
    "rinna Co., Ltd.": "JP",
    "Fachhochschule Karlsruhe, Hochschule für Technik": "DE",
    "Department of Computer Science and Engineering, The Chinese University of Hong Kong": "HK",
    "Department of Computer Science, University of Massachusetts at Amherst": "US",
    "CS Department, TU Darmstadt, TU Darmstadt": "DE",
    "University of Venice": "IT",
    "Central University of Finance and Economics": "CN",
    "University of Oxford, University of Oxford": "GB",
    "Indian Institute of Technology, Patna": "IN",
    "laboratory for Physical Sciences": "US",
    "Indian Institute of Technology Delhi": "IN",
    "Max Planck Institute of Biochemistry": "DE",
    "Department of Computer Science, Whiting School of Engineering": "US",
    "Shanghai Jiao Tong University,": "CN",
    "University of Goettingen": "DE",
    "National Institutes of Health": "US",
    "London School of Economics": "GB",
    "The Univerisity of Hong Kong": "HK",
    "Czech Technical University of Prague": "CZ",
    "Massachusetts General Hospital, Harvard University": "US",
    "Universidad de Chile": "CL",
    "NetEase, Inc.": "CN",
    "Shanghai University of Science and Technology": "CN",
    "IBM Research, Israel": "IL",
    "sensetime": "CN",
    "Toronto Metropolitan University": "CA",
    "Shanghai JiaoTong University": "CN",
    "National Institute of Informatics": "JP",
    "Alan Turing Institute": "GB",
    "University of Information Technology, VNUHCM": "VN",
    "CIIRC, Czech Technical University, Czech Technical University of Prague": "CZ",
    "Saarland University": "DE",
    "Malaviya National Institute of Technology Jaipur": "IN",
    "Vrije Universiteit Amsterdam": "NL",
    "NAVER Clova": "KR",
    "Max Delbrück Center for Molecular Medicine": "DE",
    "Pusan National University": "KR",
    "University of Florida": "US",
    "Weiyang college, Tsinghua University, Tsinghua University": "CN",
    "Colorado State University": "US",
    "Université Côte d'Azur": "FR",
    "Guilin University Of Electronic Technology": "CN",
    "Shanghai Jiaotong University": "CN",
    "Northwestern University": "US",
    "University of Potsdam": "DE",
    ", University of Illinois at Chicago": "US",
    "Imeprial College London": "GB",
    ", Tsinghua University": "CN",
    "Mitsubishi Electric Research Labs": "US",
    "Universidad Politécnica de Madrid": "ES",
    "ASAPP Inc.": "US",
    "Wuhan University": "CN",
    "Ant group": "CN",
    "Harvard Medical School": "US",
    "Ohio State University": "US",
    "ShareChat": "IN",
    "School of Mathematics and Statistics,Wuhan University": "CN",
    "Radboud University Nijmegen": "NL",
    "Fraunhofer IKS": "DE",
    "MediaTek Research": "TW",
    "Mayo Clinic": "US",
    "Freie Universität Berlin": "DE",
    "Soochow University, China": "CN",
    "University of Liverpool": "GB",
    "UT-Dallas": "US",
    "Brunel University Uxbridge": "GB",
    "Novozymes A/S": "DK",
    "University of Texas at Austin": "US",
    "University of Pittsburgh": "US",
    "J.P. Morgan AI Research": "US",
    "Hanoi University of Science and Technology": "VN",
    "Kingsoft Office": "CN",
    "Swiss Federal Institute of Technology Lausanne": "CH",
    "Department of Computer Science, Swiss Federal Institute of Technology": "CH",
    "Western University": "CA",
    "Genentech Research and Early Development": "US",
    "National Chiao Tung University": "TW",
    "University of Southern California": "US",
    "University of Geneva": "CH",
    "Apple/AIML": "US",
    "Indian Institute of Technology, Bombay": "IN",
    "Mathematical Institute, University of Oxford": "GB",
    "NII, National Institute of Informatics": "JP",
    "Rikkyo University (St. Paul's University)": "JP",
    "Duke University, Duke University": "US",
    "Irt SystemX": "FR",
    "Product Genius, Inc": "US",
    "Xerra Earth Observation Institute": "UNK",
    "Udeer.AI": "UNK",
    "Department of Computer Science, Columbia University": "US",
    "NEC Laboratories China": "CN",
    "Azad University, Mashhad Branch": "IR",
    "SADRI AI Lab": "UNK",
    "CMLA - ENS Paris Saclay, ENS Paris-Saclay": "FR",
    "Department of computer science and informational engineering, National Taiwan University": "TW",
    "Indian Institute of Technology, Jodhpur": "IN",
    "Department of Precision Instrument, Tsinghua University, Tsinghua University": "CN",
    "Yonsei University": "KR",
    "University of Groningen": "NL",
    "Kent State University": "US",
    "University of Southampton": "GB",
    "Isomorphic Labs": "US",
    "University of Adelaide": "AU",
    "Hamburg University of Applied Sciences": "DE",
    "University of California, Davis": "US",
    "Alibaba Group US": "US",
    "Institute of Computing Technology, Chinese Academy of Sciences": "CN",
    "nanjing university": "CN",
    "National Institute of Mental Health": "US",
    "The University of Tokyo": "JP",
    "Dankook University": "KR",
    "Facebook AI": "US",
    "University of Illinois at Chicago": "US",
    "TU Berlin": "DE",
    "EleutherAI": "US",
    "International Digital Economy Academy (IDEA)": "CN",
    "Konyang University Hospital": "UNK",
    "Institute of Information Engineering，Chinese Academy of Sciences": "CN",
    "University of Victoria": "CA",
    "university of Mons": "BE",
    "University of Waterloo": "CA",
    "Korea Advanced Institute of Science & Technology": "KR",
    "Indian Institute of Technology Bombay": "IN",
    "Sensetime Ltd.": "CN",
    "Tencent TiMi Studio": "CN",
    "University of Auckland": "NZ",
    "Yerevan State University": "AM",
    "Intrinsic Innovation LLC": "US",
    "Imperial College London, Imperial College London": "GB",
    "University of Virginia, Charlottesville": "US",
    "University of Konstanz": "DE",
    "University of Illinois at Urbana Champaign": "US",
    "Fractal": "US",
    "Hyundai Mobis": "KR",
    "University of Delaware": "US",
    "CISPA, Helmholtz Center for Information Security": "DE",
    "University of Pisa": "IT",
    "Georg-August Universität Göttingen": "DE",
    "Ecole polytechnique": "FR",
    "Flatiron Institute, Simons Foundation": "US",
    "Department of Computer Science, ETHZ - ETH Zurich": "CH",
    "School of Computer and Communication Sciences, EPFL - EPF Lausanne": "CH",
    "International Institute of Information Technology, Hyderabad, International Institute of Information Technology Hyderabad": "IN",
    "LG AI Research": "KR",
    "Inner Mongolia University": "CN",
    "Chinese Academy of Sciences, Institute of Software": "CN",
    "LIRIS, CNRS": "FR",
    "International Business Machines (IBM)": "US",
    "German Research Centre for AI": "DE",
    "Universite Cote d'Azur": "FR",
    "Indian Institute of Science, Dhirubhai Ambani Institute Of Information and Communication Technology": "IN",
    "2nd Military Medical University": "CN",
    "Heidelberg University, Ruprecht-Karls-Universität Heidelberg": "DE",
    "Australian National University": "AU",
    "CISPA, saarland university, saarland informatics campus": "DE",
    "Technion - Israel Institute of Technology": "IL",
    "LISN": "FR",
    "YerevaNN research Lab": "AM",
    "Universität Ulm": "DE",
    "University of Florence": "IT",
    "Instituto Nacional de Matemática Pura e Aplicada - IMPA": "BR",
    "Qilu University of Technology": "CN",
    "Czech Technical Univeresity in Prague, Czech Technical University of Prague": "CZ",
    "MPI-SWS": "DE",
    "Faulty of Applied Sciences": "UNK",
    "Snap Inc.": "US",
    "KAIST": "KR",
    "JD.com Silicon Valley Research Center": "US",
    "Fraunhofer Institute for Cognitive Systems IKS": "DE",
    "Saige Research": "UNK",
    "Fullong Tech.": "UNK",
    "Chinese University of Hong Kong, Shenzhen": "CN",
    "Open University of Israel": "IL",
    "Sun Yat-Sen University": "CN",
    "University of Tennessee, Knoxville": "US",
    "Huawei Noah's Ark Lab": "CN",
    "Center for Information and Language Processing": "UNK",
    "University of New Brunswick": "CA",
    "School of Computer Science, Carnegie Mellon University": "US",
    "Shanghai University of Finance and Economics": "CN",
    "VERSES": "UNK",
    "University of Basel": "CH",
    "National Institute of Science Education and Research": "IN",
    "Sigma Cognition": "UNK",
    "Zhejiang University NIT": "CN",
    "Robert Bosch GmbH, Bosch": "DE",
    "Central South University": "CN",
    "Boston University": "US",
    "Universität Duisburg-Essen": "DE",
    "CSIRO's Data61": "AU",
    "westlake university": "CN",
    "University of Luxemburg": "LU",
    "POLIXIR": "UNK",
    "University of Rochester": "US",
    "ETH Zürich": "CH",
    "Intel AI Research": "US",
    "Sejong University": "KR",
    "Universite of Paris-saclay": "FR",
    "Okinawa Institute of Science and Technology (OIST)": "JP",
    "Microsoft Inc": "US",
    "ByteDance AI Lab": "CN",
    "Poznan University of Technology": "PL",
    "ningbo zhoushan port company limited": "CN",
    "Stability AI": "GB",
    "INSAIT": "IT",
    "University of North Carolina at Chapel Hill": "US",
    "Nankai University": "CN",
    "RIKEN AIP": "JP",
    "SalesForce": "US",
    "Kyoto University": "JP",
    "Department of Informatics, University of Zurich, University of Zurich": "CH",
    "University of Genoa": "IT",
    "IIIT Bangalore": "IN",
    "Kempelen Institute of Intelligent Technologies": "HU",
    "Huazhong Agricultural University": "CN",
    "Nanjing University of Information Science and Technology": "CN",
    "National Institute of Water and Atmospheric Research": "NZ",
    "Computer Science Department, University of California, Los Angeles": "US",
    "uef": "FI",
    "University of Twente": "NL",
    "Technology Innovation Institute": "AE",
    "Hong Kong University of Science and Technology": "HK",
    "Universidad de Alicante": "ES",
    "Institut des systèmes intelligents et robotique (ISIR) - Sorbonne Université": "FR",
    "Department of Computer Science and Technology, Tsinghua University": "CN",
    "Naval Postgraduate School": "US",
    "International Institute of information technology, bangalore": "IN",
    "Shanghai Fudan Microelectronics Group Co., Ltd": "CN",
    "GSK plc": "GB",
    "Gladstone Institutes": "US",
    "University of Illinois at Urbana-Champaign ": "US",
    "Florida Atlantic University": "US",
    "North China Electric Power University": "CN",
    "RIKEN": "JP",
    "Universität des Saarlandes": "DE",
    "Shandong University of Finance and Economics": "CN",
    "VISA": "US",
    "Czech Technical University in Prague": "CZ",
    "Salk Institute": "US",
    "BFH - Bern University of Applied Sciences": "CH",
    "Ningxia University": "CN",
    "University of Strathclyde": "GB",
    "Samaya AI": "UNK",
    "Budapest University of Technology and Economics": "HU",
    "Tianjin Medical University": "CN",
    "Graphic Era University": "IN",
    "Sony Canada Ltd.": "CA",
    " Tsinghua University": "CN",
    "East China University of Science and Technology": "CN",
    "Steklov Institute of Mathematics at St. Petersburg": "RU",
    "JD Explore Academy": "CN",
    "Higher School of Economics, Higher School of Economics": "RU",
    "National Tsing Hua University": "TW",
    "iSize": "IL",
    "York University": "CA",
    "Leiden University, Leiden University": "NL",
    "Indian Institute of Technology Bombay, Indian Institute of Technology, Bombay": "IN",
    "Rensselaer Polytechnic Institute": "US",
    "Heidelberg University": "DE",
    "iim": "IN",
    "Universität Innsbruck": "AT",
    "University of Illinois, Chicago": "US",
    "University Kaiserslautern-Landau": "DE",
    "The University of Manchester": "GB",
    "Electrical Engineering & Computer Science, Massachusetts Institute of Technology": "US",
    "SUN YAT-SEN UNIVERSITY": "CN",
    "School of Computer Science, Wuhan University": "CN",
    "Pingan Technology": "CN",
    "Swiss Federal Institute of Technology Zurich": "CH",
    "University of Edinburgh": "GB",
    "ETHZ - ETH Zurich": "CH",
    "University of Chicago Laboratory Schools": "US",
    "Warsaw University of Technology": "PL",
    "École Polytechnique IP-Paris": "FR",
    "Electrical Engineering & Computer Science Department, University of California, Berkeley": "US",
    "Hebei University of Science and Technology": "CN",
    "Science and Technology Facilities Council": "GB",
    "Amherst College": "US",
    "WESTLAKE UNIVERSITY": "CN",
    "SUN YAT-SEN UNIVERSITY, Tsinghua University": "CN",
    "Meituan": "CN",
    "Queensland University of Technology": "AU",
    "Noeon Research": "UNK",
    "University of Leicester": "GB",
    "National Tsinghua University": "TW",
    "Technical University Munich": "DE",
    "Novo Nordisk": "DK",
    "Kobe University": "JP",
    "INRIA": "FR",
    "University of Glasgow": "GB",
    "National Institute for mathematical Sciences": "KR",
    "University Paris-Saclay": "FR",
    "Wayve": "GB",
    "Université Paris 13": "FR",
    "Sberbank": "RU",
    "Department of Computer Science, University of North Carolina at Chapel Hill": "US",
    "Preferred Networks, Inc.": "JP",
    "Redpoll": "UNK",
    "Beijing Jiaotong University": "CN",
    "University of North Carolina at Charlotte": "US",
    "Gwangju Institute of Science and Technology": "KR",
    "Utah State University": "US",
    "Syracuse University": "US",
    "Shanghai Institute for Advanced Study of Zhejiang University": "CN",
    "Institute of automation, Chinese academy of science, Chinese Academy of Sciences": "CN",
    "London Mathematical Laboratory": "GB",
    "THE CHINESE UNIVERSITY OF HONG KONG, SHENZHEN": "CN",
    "Tokyo University, Tokyo Institute of Technology": "JP",
    "HKUST(GZ)": "CN",
    "Nagoya University": "JP",
    "Arizona State University": "US",
    "Universität Osnabrück": "DE",
    "NCSOFT Co.": "KR",
    "Indian Institute of Technology Jodhpur": "IN",
    "Ludong University": "CN",
    "University of Toronto, University of Toronto": "CA",
    "Université de Rouen": "FR",
    "National Yang-Ming Chiao Tung University": "TW",
    "Johns Hopkins University Applied Physics Laboratory": "US",
    "University of Illinois, Urbana-Champaign": "US",
    "University of Minnesota": "US",
    "Technische Hochschule Ingolstadt": "DE",
    "Albert-Ludwigs-Universität Freiburg": "DE",
    "AWS": "US",
    "Hayden AI": "UNK",
    "VUNO": "UNK",
    "PASQAL SAS": "FR",
    "Pennsylvania State University": "US",
    "Tsinghua University, Tsinghua University": "CN",
    "Rheinisch Westfälische Technische Hochschule Aachen": "DE",
    "Technical University of Munich": "DE",
    "Zhejiang Lab, Zhejiang Lab": "CN",
    "Samsung Electronics": "KR",
    "Harvard T.H. Chan School of Public Health": "US",
    "University of Sheffield": "GB",
    "International Institute of Information Technology Hyderabad, Dhirubhai Ambani Institute Of Information and Communication Technology": "IN",
    "State University of New York at Stony Brook": "US",
    "Brandeis University": "US",
    "Virginia Tech": "US",
    "MIPT": "RU",
    "University of the West of England, Bristol": "GB",
    "Université de Strasbourg": "FR",
    "Politecnico di Torino": "IT",
    "Xiamen University Malaysia": "MY",
    "Eberhard-Karls-Universität Tübingen": "DE",
    ", University of California, Santa Barbara": "US",
    "Hochschule Fulda": "DE",
    "Scale AI": "US",
    "Meta (Facebook) AI": "US",
    "Ecole Normale Superieure Paris-Saclay": "FR",
    "Indian Institute of Technology Kharagpur": "IN",
    "Qingdao University": "CN",
    "School of Computer Science": "UNK",
    "CAICT": "CN",
    "IBM": "US",
    "University of Sharjah": "AE",
    "NYU, New York University": "US",
    "Korea Institute of Energy Technology": "KR",
    "Horizon Robotics": "CN",
    "Universität Vienna": "AT",
    "Computer Science and Artificial Intelligence Laboratory, Electrical Engineering & Computer Science": "US",
    "ENSTA Paris": "FR",
    "Shandong University": "CN",
    "RISE Research Institutes of Sweden": "SE",
    "Uppsala University": "SE",
    "ASAPP": "US",
    "genentech": "US",
    "Institute for Research in Fundamental Sciences": "IR",
    "University of Pennsylvania, University of Pennsylvania": "US",
    "National Technical University of Athens": "GR",
    "Mila, University of Montreal": "CA",
    "Umea University": "SE",
    "CS Department, TU Dortmund University, Germany, TU Dortmund": "DE",
    "C3 AI": "US",
    "INRIA Paris": "FR",
    "Tohoku University": "JP",
    "Food and Drug Administration": "US",
    "Chinese University of Hong Kong, The Chinese University of Hong Kong": "HK",
    "École de technologie supérieure, Université du Québec": "CA",
    "Macao Polytechnic University": "MO",
    "The Second Affiliated HospiGuangzhou University of Traditional Chinese Medicine": "CN",
    "School of Statistics, Renmin University of China": "CN",
    "University of Calgary": "CA",
    "ServiceNow Research": "US",
    "Criteo": "FR",
    "ATR": "FR",
    "Chungnam National University": "KR",
    "INSA Rouen Normandy": "FR",
    "Electrical Engineering and Computer Sciences, University of California Berkeley": "US",
    "Qom University of Technology": "IR",
    "Sapienza University of Rome": "IT",
    "Technical University of Denmark": "DK",
    "Dongguan University of Technology": "CN",
    "University of Michigan - Ann Arbor": "US",
    "University of Central Florida": "US",
    "University of Turku": "FI",
    "EURECOM": "FR",
    "École Polytechnique de Montréal, Université de Montréal": "CA",
    "Friedrich-Alexander Universität Erlangen-Nürnberg": "DE",
    "Bocconi University": "IT",
    "Spotify": "SE",
    "Universität Kaiserslautern": "DE",
    "National Central University": "TW",
    "Institute of Computing Technology, Chinese Academy of Sciences; University of Chinese Academy of Sciences": "CN",
    "LIPN, Université Sorbonne Paris Nord": "FR",
    "University of Queensland": "AU",
    "ADIA": "AE",
    "ITMO University": "RU",
    "ANTLAB": "UNK",
    "University of California, San Francisco": "US",
    "University of New South Wales": "AU",
    "University Paris 13, Université Paris Nord (Paris XIII)": "FR",
    "Sony Research India": "IN",
    "Université François Rabelais de Tours": "FR",
    "Chung-Ang University": "KR",
    "Roche": "CH",
    "National Technological University": "AR",
    "Yandex Research Lab at HSE University": "RU",
    "Norwegian University of Science and Technology": "NO",
    "Allen Institute": "US",
    "University of Munich, Ludwig-Maximilians-Universität München": "DE",
    "Ohio State University, Columbus": "US",
    "Université de Neuchâtel": "CH",
    "Guide Labs": "UNK",
    "FAIR, Meta": "US",
    "QCraft Inc": "US",
    "State University of New York at Binghamton": "US",
    "Meta Platforms Inc": "US",
    "Wenzhou University": "CN",
    "ZJU-Hangzhou Global Scientific and Technological Innovation Center": "CN",
    "Xianda College of Economics and Humanities Shanghai International Studies University": "CN",
    "Fraunhofer ITWM": "DE",
    "Insititute Of Computing Technology, Chinese Academy of Sciences": "CN",
    "Fractal Analytics Ltd.": "IN",
    "Department of Computer Science, University of Maryland, College Park": "US",
    ", Hebrew University of Jerusalem": "IL",
    "henan normal university": "CN",
    "University of Technology Sydney": "AU",
    "Oak Ridge National Laboratory": "US",
    "Max Planck Institute for Intelligent Systems": "DE",
    "Indian Institute of Technology Madras": "IN",
    "Hong Kong Baptist University": "HK",
    "Chinese Academy of SciencesComputer Network Information Center": "CN",
    "King Abdullah University of Science and Technology": "SA",
    "Ecole Nationale des Ponts et Chausees": "FR",
    "Tencent AI Lab": "CN",
    "Alpen-Adria Universität Klagenfurt": "AT",
    "Isfahan University of Technology": "IR",
    "Beckhoff Automation": "DE",
    "University of Bergen": "NO",
    "Embry-Riddle Aeronautical University": "US",
    "Paris-Lodron-University of Salzburg": "AT",
    ", Johann Wolfgang Goethe Universität Frankfurt am Main": "DE",
    "lenovo": "CN",
    "International Higher School for Advanced Studies Trieste": "IT",
    "DeepMind": "GB",
    "University of Siena": "IT",
    "CHUV - University Hospital Lausanne": "CH",
    "BAAI": "CN",
    "Toyota Central R&D Labs., Inc.": "JP",
    "Beijing DP Technology Co., Ltd.": "CN",
    "Google Brain Robotics & Columbia University": "US",
    "Télécom ParisTech": "FR",
    "Tampere University": "FI",
    "Technion - Israel Institute of Technology, Technion - Israel Institute of Technology": "IL",
    "Harbin Institute of Technology at Weihai": "CN",
    "Bilkent University": "TR",
    "Universität Konstanz": "DE",
    "Mediatek": "TW",
    "Shanghai AI Labratory": "CN",
    "UCLA, University of California, Los Angeles": "US",
    "Loughborough University": "GB",
    "IDEAS NCBR": "UNK",
    "Meta AI (FAIR)": "US",
    "physical intelligence": "UNK",
    "University of Science and Technology Beijing": "CN",
    "Broad Institute": "US",
    "University of Mannheim": "DE",
    "Baichuan": "CN",
    "Institute of Geographic Sciences and Natural Resources Research, CAS": "CN",
    "Gatsby Computational Neuroscience Unit": "GB",
    "EHESS": "FR",
    "Hong Kong Polytechnic University": "HK",
    "International Institute of Information Technology Hyderabad": "IN",
    "Department of Informatics, Technische Universität München": "DE",
    "Computer Science Departmen, Technion-Israel Institute of Technology": "IL",
    "University of Trento": "IT",
    "Pohang University of Science and Technology": "KR",
    "Taita Taveta University": "KE",
    "Shanghai Polytechnic University": "CN",
    "Osaka University, Tokyo Institute of Technology": "JP",
    "University of Tuebingen": "DE",
    "Indian Institute of Technology, Bombay, Dhirubhai Ambani Institute Of Information and Communication Technology": "IN",
    "UMONS": "BE",
    "Institute of automation, Chinese academy of science": "CN",
    "University of Montreal, University of Montreal": "CA",
    "Swiss Federal Institute of Technology": "CH",
    "University of Edinburgh, University of Edinburgh": "GB",
    "LMU Munich": "DE",
    "IRT Saint-Exupéry": "FR",
    "Institute of Mathematics for Industry, Kyushu University": "JP",
    "University of South China": "CN",
    "Chinese Institute for Brain Research, Beijing": "CN",
    "Instituto Superior Técnico": "PT",
    "Ecole Centrale de Lyon": "FR",
    "Radboud University": "NL",
    "Xi'an University of Electronic Science and Technology": "CN",
    "Ecole Nationale de la Statistique et de l'Administration Economique": "UNK",
    "Electronics and Telecommunications Research Institute": "KR",
    "Institute for AI Industry Research, Tsinghua University": "CN",
    "Dana-Farber Cancer Institute": "US",
    "Birmingham Newman University, UK": "GB",
    "University of Electro-Communications": "JP",
    "Toyota Technological Institute at Chicago": "US",
    "Helmholtz Center Munich": "DE",
    "Chinese Academy of Sciences, Chinese Academy of Sciences": "CN",
    "Layer6 AI": "CA",
    ", University of Texas at Austin": "US",
    "Getulio Vargas Foundation": "BR",
    "Harbin Institute of Technology, shenzhen": "CN",
    "Peking University, Tsinghua University": "CN",
    "University of Texas, Austin": "US",
    "Technische Universität Dortmund": "DE",
    "DisneyResearch|Studios": "US",
    "Universidade Federal de Santa Catarina": "BR",
    "Tel Aviv University, Tel Aviv University": "IL",
    "Télécom Paris": "FR",
    "Baidu": "CN",
    "Aalto University": "FI",
    "National Innovation Institute of Defense Technology": "CN",
    "SI Analytics": "UNK",
    "University of Tromsø": "NO",
    "Utrecht University": "NL",
    "Max Planck Institute for Psycholinguistics": "NL",
    "The Francis Crick Institute": "GB",
    "Meta Artificial Intelligence Research": "US",
    ", State University of New York at Stony Brook": "US",
    "AGH University of Science and Technology": "PL",
    "Zhongnan University of Economics and Law": "CN",
    "Liaoning University": "CN",
    "Eurecom": "FR",
    "Universität Hildesheim": "DE",
    "Noodle AI": "UNK",
    "Department of Electronic Engineering, Tsinghua University": "CN",
    "Qualcomm": "US",
    "Tianjin University": "CN",
    "Du Xiaoman Technology(BeiJing)": "CN",
    "Stanford Existential Risks Initiative": "US",
    "CS Department, University of Freiburg, Germany, Albert-Ludwigs-Universität Freiburg": "DE",
    "Anhui University": "CN",
    "national university of singaore, National University of Singapore": "SG",
    "Bernstein center for computational neuroscience": "DE",
    "Indian Institute of Technology , Kanpur": "IN",
    "SK Telecom AI&CO": "KR",
    "University of Antwerp": "BE",
    "MIT World Peace University": "IN",
    "Faculty of Electrical Engineering and Computing, University of Zagreb": "HR",
    "LinkedIn": "US",
    "Université Pierre et Marie Curie - Paris 6, Sorbonne Université - Faculté des Sciences (Paris VI)": "FR",
    "Hanyang University": "KR",
    "Harbin Institute of Technology (shenzhen)": "CN",
    "Department of Computer and Information Science, School of Engineering and Applied Science": "UNK",
    "Toyota Motor Corporation": "JP",
    "Kazan Federal University": "RU",
    "Institute of automation, Chinese Academy of Sciences": "CN",
    "DA-IICT": "IN",
    "GSK": "GB",
    "Old Dominion University": "US",
    "Military Institute of Science and Technology": "BD",
    "Laval university": "CA",
    "Graz University of Technology": "AT",
    "Singapore University of Technology and Design": "SG",
    "Kyushu University": "JP",
    "University of Wisconsin, Madison": "US",
    "Université Paris Nord (Paris XIII)": "FR",
    "Beijing Institute for General Artificial Intelligence": "CN",
    "CISPA Helmholtz Center for Information Security": "DE",
    "Soochow University": "CN",
    "Temple University": "US",
    "Jilin University": "CN",
    "Jarvis Research Center, Tencent YouTu Lab": "CN",
    "INSA de Rouen": "FR",
    "Institute of Logic and Computation, Technische Universität Wien": "AT",
    "VU Amsterdam": "NL",
    "Moonshot AI Ltd": "GB",
    "Boston College": "US",
    "University of Freiburg, Albert-Ludwims-Universität Freiburg": "DE",
    "Bahir Dar University, Bahir Dar Institute of Technology": "ET",
    "Nanjing University of Science and Technology": "CN",
    "Otto-von-Guericke Universität Magdeburg": "DE",
    "Bar Ilan University, Technion": "IL",
    "Oxofrd, University of Oxford": "GB",
    "Baidu Inc.": "CN",
    "DLR": "DE",
    "Qualcomm Inc, QualComm": "US",
    "State Grid Power Supply Co. Ltd.": "CN",
    "University of the Chinese Academy of Sciences": "CN",
    "A*STAR": "SG",
    "ByteDance, Inc.": "CN",
    "Ben-Gurion University of the Negev": "IL",
    "Research, Google": "US",
    "Wuhan University, Tsinghua University": "CN",
    "Prescient Design - Genentech, Roche": "US",
    "Artificial Intelligence Research Lab.": "UNK",
    "Florida State University": "US",



    "Florida International University": "US",

    "Flatiron Institute": "US",
    "I I T Ropar, India": "IN",
    "LJLL, UMR 7198": "FR",
    "IDEAS-NCBR": "PL",
    "DATAGRID Inc.": "UNK",
    "Beijing Normal University": "CN",
    "Minds and Company": "UNK",
    "MedaiTek Research": "TW",
    "Sorbonne Université - Faculté des Sciences (Paris VI)": "FR",
    "AgroParisTech": "FR",
    "Texas A&M University - College Station": "US",
    "ILIA": "UNK",
    "University College London, University of London": "GB",
    "German Aerospace Center (DLR)": "DE",
    "Zaheer": "UNK",
    "University of Osnabrück": "DE",
    "Université Laval": "CA",
    "Machine Learning Department, School of Computer Science": "UNK",
    "Pukyong National University": "KR",
    ", Rutgers University": "US",
    "The University of Texas at Dallas": "US",
    "kuaishou techology": "CN",
    "State University of New York, Buffalo": "US",
    "The Hong Kong Polytechnic University, Hong Kong Polytechnic University": "HK",
    "Shanghai Institute of Materia Medica": "CN",
    "Institut National des Sciences Appliquées de Rouen": "FR",
    "Helsing": "UNK",
    "OPPO Inc.": "CN",
    "Leiden University": "NL",
    "Department of Computer Science, University of Wisconsin - Madison": "US",
    "Politecnico di Milano": "IT",
    "Hanbat National University": "KR",
    "The University of Melbourne": "AU",
    "University of Rennes": "FR",
    "Department of computer science and technology, Tsinghua University": "CN",
    "Universita' degli studi di Padova": "IT",
    "Mirelo AI": "UNK",
    "The University of Sydney": "AU",
    "Georgia Tech Research Institute": "US",
    "Universität Hamburg": "DE",
    "Paul G. Allen School of Computer Science and Engineering, University of Washington": "US",
    "Queen Mary, University of London": "GB",
    "Institute of Statistical Mathematics, Japan": "JP",
    "Apple AI/ML": "US",
    "Naver Labs Europe": "FR",
    "Université de Rennes, France": "FR",
    "Hefei University of Technology": "CN",
    "University of California, Irvine": "US",
    "Department of Computer Science, University of Oxford": "GB",
    "The University of Tokyo, The University of Tokyo": "JP",
    "Victoria University": "AU",
    "University of Milan": "IT",
    "Korea University": "KR",
    "Tencent TiMi L1 Studio": "CN",
    "Vishwakarma Institute of technology Pune": "IN",
    "Deeping Source": "UNK",
    "ITU of Punjab Lahore, Pakistan": "PK",
    "Vector Institute/Dalhousie University": "CA",
    "Onera - The french aerospace lab": "FR",
    "German Research Center for AI": "DE",
    "US FDA": "US",
    "Polytechnique Montreal": "CA",
    "Université de Lausanne": "CH",
    "Sogang University": "KR",
    "AIST, National Institute of Advanced Industrial Science and Technology": "JP",
    "Concordia University": "CA",
    "Whiting School of Engineering": "US",
    "IRT systemX": "FR",
    "SLAC National Accelerator Laboratory": "US",
    "Universidade de São Paulo": "BR",
    "Vertebra": "UNK",
    "SystemX": "FR",
    "SI-Analytics": "UNK",
    "CNR": "IT",
    "Group Innovation, Volkswagen Group": "DE",
    "CNRS": "FR",
    "National Central University, Taiwan": "TW",
    "Universitat Pompeu Fabra": "ES",
    "KAIST, Korea Advanced Institute of Science & Technology": "KR",
    "Department of Computing Science, University of Alberta": "CA",
    "Université de Rennes": "FR",
    "Macquarie University": "AU",
    "King's College London": "GB",
    "AstraZeneca": "GB",
    "School of Computer Science and Technology, Beijing Institute of Technology": "CN",
    "Inworld AI": "UNK",
    "Laboratory for Physical Sciences": "US",
    "Institute of Computer Science and Engineering": "UNK",
    "Shenzhen Research Institute of Big Data": "CN",
    "Rheinische Friedrich-Wilhelms Universität Bonn": "DE",
    "University of Luxembourg": "LU",
    "College of Computing, Georgia Institute of Technology": "US",
    "Department of Computer Science, University of Toronto": "CA",
    "Provenance AI Inc": "UNK",
    "Sung Kyun Kwan University": "KR",
    "Google Brain": "US",
    "University of International Business and Economics": "CN",
    "University of Bristol": "GB",
    "NVIDIA AI": "US",
    "Southern Medical University": "CN",
    "Graphcore Ltd": "GB",
    "Teraflop AI": "UNK",
    "Allen Institute for Artificial Intelligence / UW": "US",
    "Télécom SudParis": "FR",
    "Loughborough University London": "GB",
    "Université Paris-Cité": "FR",
    "National Institute of Science Education and Reasearch": "IN",
    "Aichi Sangyo University": "JP",
    "Northwestern University, Northwestern University": "US",
    "University of Manchester": "GB",
    "Korea Advanced Institute of Science and Technology": "KR",
    "School of IoT Engineering": "UNK",
    "Sony Research India, Bangalore": "IN",
    "Fraunhofer Institute IAIS, Fraunhofer IAIS": "DE",
    "Shanghai University": "CN",
    "Universität zu Lübeck": "DE",
    "Wake Forest University School of Medicine": "US",
    "Universiteit Gent": "BE",
    "VinUniversity": "VN",
    "Ocean University of China": "CN",
    "New York University, Abu Dhabi": "AE",
    "Nanjing University of Aeronautics and Astronautics": "CN",
    "Aarhus University": "DK",
    "nPlan Limited": "GB",
    "Electrical Engineering and Computer Sciences, University of California, Berkeley": "US",
    "KTH": "SE",
    "Google/DeepMind": "GB",
    "School of mathematical Science, Peking University, Peking University": "CN",
    "CentraleSupelec": "FR",
    "University of Wollongong": "AU",
    "The Swiss AI Lab IDSIA": "CH",
    "Istanbul Technical University": "TR",
    "Beijing University of Technology": "CN",
    "Sandia National Laboratories": "US",
    "University of Liege": "BE",
    "University of Oslo": "NO",
    "UC Berkeley, University of California, Berkeley": "US",
    "Universite Paris-Saclay": "FR",
    "TU Braunschweig": "DE",
    "NuMind": "UNK",
    "NCSOFT Corp": "KR",
    "Southern Unviersity of Science and Technology": "CN",
    "King Saud University": "SA",
    "IBM, International Business Machines": "US",
    "The Second Affiliated Hospital of Guangzhou University of Traditional Chinese Medicine": "CN",
    "01 Intelligence": "UNK",
    "Southern University of Science and Technology": "CN",
    "Koc University": "TR",
    "Genentech": "US",
    "Tel Aviv University, Technion": "IL",
    "Hebrew U and Google": "IL",
    "University of Sydney, University of Sydney": "AU",
    "Zhejiang Lab China": "CN",
    "Bahir Dar University": "ET",
    "Universidad de Zaragoza": "ES",
    "Montreal Institute for Learning Algorithms, University of Montreal, University of Montreal": "CA",
    "Morgan Stanley": "US",
    "University of Freiburg, Albert-Ludwigs-Universität Freiburg": "DE",
    "Eotvos Lorand University, Eötvös Lorand University": "HU",
    "NAVER AI Lab": "KR",
    "Vanderbilt University": "US",
    "Universität Bielefeld": "DE",
    "Institute of Computer Engineering": "UNK",
    "MeiTuan": "CN",
    "EleutherAI Institute": "US",
    "Computer Network Information Center,Chinese Academy of Sciences": "CN",
    ", Brown University": "US",
    "Delft University of Technology": "NL",
    "Faculty of Information Science and Technology, Hokkaido University": "JP",
    "University of Saskatchewan": "CA",
    "William Marsh Rice University": "US",
    "Bahir Dar Institute of Technology": "ET",
    "Mediatek Research": "TW",
    "Indian Institute of Science, Indian institute of science, Bangalore": "IN",
    "Google Brain  ": "US",
    "HSLU - Lucerne University of Applied Sciences and Arts": "CH",
    "xidian university": "CN",
    "TU Wien": "AT",
    "Hankuk University of Foreign Studies": "KR",
    "University of the Witwatersrand": "ZA",
    "Meta Reality Labs": "US",
    "Higher School of Economics": "RU",
    "CS Department, TU Darmstadt, Technische Universität Darmstadt": "DE",
    "Guangdong University of Technology": "CN",
    "eim": "UNK",
    "Department of Mathematical Sciences, Tsinghua University": "CN",
    "Google Inc.": "US",
    "Beihang  University": "CN",
    "University of California, San Diego, University of California, San Diego": "US",
    "Pontificia Universidad Catolica de Chile": "CL",
    "Norwegian Computing Center": "NO",
    "Facultés Universitaires Notre-Dame de la Paix": "UNK",
    "Dhirubhai Ambani Institute of Information and communication Technology": "IN",
    "National Yang-Ming Chiao-Tung University": "TW",
    "Duisburg-Essen University": "DE",
    "Southwest University of Finance and Economics": "CN",
    "Computer Science Department, Stanford University": "US",
    "IHES": "FR",
    "Université Leipzig": "DE",
    "INSA de Lyon": "FR",
    "Central China Normal University": "CN",
    "Anhui Normal University": "CN",
    "Max-Planck Institute for Informatics": "DE",
    "Institut de neurobiologie de la méditerranée": "FR",
    "Consiglio Nazionale delle Ricerche": "IT",
    "UC San Diego, University of California, San Diego": "US",
    "Chinese University of Hong Kong": "HK",
    "Medizinische Universität Innsbruck": "AT",
    "School of Mathematical Sciences, Shanghai Jiao Tong University": "CN",
    "Carper.AI": "UNK",
    "Rochester Institute of Technology": "US",
    "University of Shanghai for Science and Technology": "CN",
    "University of Illinois Urbana-Champaign": "US",
    "University of Trieste": "IT",
    "University of Roma \"La Sapienza\"": "IT",
    "Meta ": "US",
    "Meta AI Research": "US",
    " Pr(Ai)²R Group": "UNK",
    "ByteDance Ltd": "CN",
    "German Aerospace Center": "DE",
    "University of Electronic Science and Technology of China": "CN",
    "South China University": "CN",
    "Christian-Albrechts-Universität Kiel": "DE",
    "University of Stuttgart": "DE",
    "Sun Yat-sen University": "CN",
    "NEC Laboratories Europe": "NL",
    "Masaryk University, Brno": "CZ",
    "Johannes Kepler Universität Linz": "AT",
    "Nanrui Group Co., Ltd": "CN",
    "German Cancer Research Center": "DE",
    "University of Illinois Urbana Champaign": "US",
    "Temasek Life Sciences Laboratory / National University of Singapore": "SG",
    "Institute of Software, Chinese Academy of Sciences": "CN",
    "JD.com, Inc.": "CN",
    "Fujitsu Research and Development Center Co. Ltm.": "JP",
    "Tufts University": "US",
    "Huzhou University": "CN",
    "Department of computer science and information engineering, National Taiwan University": "TW",
    "Bupt": "CN",
    "Korea Institute of Science and Technology": "KR",
    "George Washington University": "US",
    "Banca d'Italia": "IT",
    "Biomedical Engineering, Tsinghua University": "CN",
    "Karlsruhe Institute of Technology": "DE",
    "Santa Fe Institute": "US",
    "University of Southern Denmark - SDU": "DK",
    "Universidad de Granada": "ES",
    "Chongqing University": "CN",
    "University of St Andrews": "GB",
    "Fudan University, Tsinghua University": "CN",
    "IIIS, Tsinghua University": "CN",
    "Lawrence Berkeley National Lab": "US",
    "Institut de recherche technologique Saint-Exupéry": "FR",
    "Texas A&M": "US",
    "Apple AI Research": "US",
    "Borealis AI": "CA",
    "Ben Gurion University of the Negev, Technion": "IL",
    "Tobb Economics and Technology University": "TR",
    "Posts & Telecommunications Institute of Technology": "TH",
    "DATAGRID": "UNK",
    "Rice University": "US",
    "NCSR “Demokritos”": "GR",
    "Carleton University": "CA",
    "Twitter": "US",
    "Fraunhofer IIS": "DE",
    "Harbin Institute of Technology, Shenzhen": "CN",
    "The University of Hong Kong": "HK",
    "Computer Science Department, Technion - Israel Institute of Technology": "IL",
    "Technische Universität München": "DE",
    "Heriot-Watt University": "GB",
    "Coresystems": "UNK",
    "University of California, Riverside": "US",
    "Meta platforms inc": "US",
    "École Polytechnique": "FR",
    "Department of Computer Science, Indian Institute of Technology, Madras, Indian Institute of Technology, Madras": "IN",
    "XiJing University": "CN",
    "Kyung Hee University": "KR",
    "Ningbo Beilun Third Container Terminal Co., Ltd": "CN",
    "Xi'an Jiaotong-Liverpool University": "CN",
    "Roche / Genentech": "US",
    "Università della Svizzera Italiana": "CH",
    "Technische Universität Dresden": "DE",
    "Recursion": "US",
    "Layer 6 AI": "CA",
    "Beijing Institute of Mathematical Sciences and Applications": "CN",
    "The Chinese University of Hong Kong (Shenzhen)": "CN",
    "University of Hawaii, Manoa": "US",
    "Allen Institute for Artificial Intelligence": "US",
    "Electrical Engineering & Computer Science Department, University of California Berkeley": "US",
    "Westlake University": "CN",
    "Aalborg University": "DK",
    "Researcher at Beijing Academy of Artificial Intelligence": "CN",
    "Eötvös Loránd University": "HU",
    "Google Deepmind": "GB",
    "International Curriculum Centre, RDFZ": "CN",
    "Ecole Normale Superieure Paris": "FR",
    "Université de Rouen - Haute Normandie": "FR",
    "Academia Sinica": "TW",
    "Linköping University": "SE",
    "Institute of Information Science, Academia Sinica": "TW",
    "Xi'an University": "CN",
    "The Wharton School, University of Pennsylvania": "US",
    "ant group": "CN",
    "Max Planck Institute for Biological Cybernetics, Max-Planck Institute": "DE",
    "Silo AI": "FI",
    "Universiteit Antwerpen": "BE",


    "Ecole Nationale de la Statistique et de la Administration Economique": "FR",
    "Universität Leipzig": "DE"

}
