"""
Configuration and constants for the analytics pipeline.
"""

from typing import Dict, List, Any

# Country code mappings
COUNTRY_CODE_MAP = {
    "AF": "Afghanistan",
    "AX": "Aland Islands",
    "AL": "Albania",
    "DZ": "Algeria",
    "AS": "American Samoa",
    "AD": "Andorra",
    "AO": "Angola",
    "AI": "Anguilla",
    "AQ": "Antarctica",
    "AG": "Antigua And Barbuda",
    "AR": "Argentina",
    "AM": "Armenia",
    "AW": "Aruba",
    "AU": "Australia",
    "AT": "Austria",
    "AZ": "Azerbaijan",
    "BS": "Bahamas",
    "BH": "Bahrain",
    "BD": "Bangladesh",
    "BB": "Barbados",
    "BY": "Belarus",
    "BE": "Belgium",
    "BZ": "Belize",
    "BJ": "Benin",
    "BM": "Bermuda",
    "BT": "Bhutan",
    "BO": "Bolivia",
    "BA": "Bosnia And Herzegovina",
    "BW": "Botswana",
    "BV": "Bouvet Island",
    "BR": "Brazil",
    "IO": "British Indian Ocean Territory",
    "BN": "Brunei Darussalam",
    "BG": "Bulgaria",
    "BF": "Burkina Faso",
    "BI": "Burundi",
    "KH": "Cambodia",
    "CM": "Cameroon",
    "CA": "Canada",
    "CV": "Cape Verde",
    "KY": "Cayman Islands",
    "CF": "Central African Republic",
    "TD": "Chad",
    "CL": "Chile",
    "CN": "China",
    "CX": "Christmas Island",
    "CC": "Cocos (Keeling) Islands",
    "CO": "Colombia",
    "KM": "Comoros",
    "CG": "Congo",
    "CD": "Congo, Democratic Republic",
    "CK": "Cook Islands",
    "CR": "Costa Rica",
    "CI": "Cote D\"Ivoire",
    "HR": "Croatia",
    "CU": "Cuba",
    "CY": "Cyprus",
    "CZ": "Czech Republic",
    "DK": "Denmark",
    "DJ": "Djibouti",
    "DM": "Dominica",
    "DO": "Dominican Republic",
    "EC": "Ecuador",
    "EG": "Egypt",
    "SV": "El Salvador",
    "GQ": "Equatorial Guinea",
    "ER": "Eritrea",
    "EE": "Estonia",
    "ET": "Ethiopia",
    "FK": "Falkland Islands (Malvinas)",
    "FO": "Faroe Islands",
    "FJ": "Fiji",
    "FI": "Finland",
    "FR": "France",
    "GF": "French Guiana",
    "PF": "French Polynesia",
    "TF": "French Southern Territories",
    "GA": "Gabon",
    "GM": "Gambia",
    "GE": "Georgia",
    "DE": "Germany",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GR": "Greece",
    "GL": "Greenland",
    "GD": "Grenada",
    "GP": "Guadeloupe",
    "GU": "Guam",
    "GT": "Guatemala",
    "GG": "Guernsey",
    "GN": "Guinea",
    "GW": "Guinea-Bissau",
    "GY": "Guyana",
    "HT": "Haiti",
    "HM": "Heard Island & Mcdonald Islands",
    "VA": "Holy See (Vatican City State)",
    "HN": "Honduras",
    "HK": "Hong Kong",
    "HU": "Hungary",
    "IS": "Iceland",
    "IN": "India",
    "ID": "Indonesia",
    "IR": "Iran, Islamic Republic Of",
    "IQ": "Iraq",
    "IE": "Ireland",
    "IM": "Isle Of Man",
    "IL": "Israel",
    "IT": "Italy",
    "JM": "Jamaica",
    "JP": "Japan",
    "JE": "Jersey",
    "JO": "Jordan",
    "KZ": "Kazakhstan",
    "KE": "Kenya",
    "KI": "Kiribati",
    "KR": "Korea",
    "KP": "North Korea",
    "KW": "Kuwait",
    "KG": "Kyrgyzstan",
    "LA": "Lao People\"s Democratic Republic",
    "LV": "Latvia",
    "LB": "Lebanon",
    "LS": "Lesotho",
    "LR": "Liberia",
    "LY": "Libyan Arab Jamahiriya",
    "LI": "Liechtenstein",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "MO": "Macao",
    "MK": "Macedonia",
    "MG": "Madagascar",
    "MW": "Malawi",
    "MY": "Malaysia",
    "MV": "Maldives",
    "ML": "Mali",
    "MT": "Malta",
    "MH": "Marshall Islands",
    "MQ": "Martinique",
    "MR": "Mauritania",
    "MU": "Mauritius",
    "YT": "Mayotte",
    "MX": "Mexico",
    "FM": "Micronesia, Federated States Of",
    "MD": "Moldova",
    "MC": "Monaco",
    "MN": "Mongolia",
    "ME": "Montenegro",
    "MS": "Montserrat",
    "MA": "Morocco",
    "MZ": "Mozambique",
    "MM": "Myanmar",
    "NA": "Namibia",
    "NR": "Nauru",
    "NP": "Nepal",
    "NL": "Netherlands",
    "AN": "Netherlands Antilles",
    "NC": "New Caledonia",
    "NZ": "New Zealand",
    "NI": "Nicaragua",
    "NE": "Niger",
    "NG": "Nigeria",
    "NU": "Niue",
    "NF": "Norfolk Island",
    "MP": "Northern Mariana Islands",
    "NO": "Norway",
    "OM": "Oman",
    "PK": "Pakistan",
    "PW": "Palau",
    "PS": "Palestinian Territory, Occupied",
    "PA": "Panama",
    "PG": "Papua New Guinea",
    "PY": "Paraguay",
    "PE": "Peru",
    "PH": "Philippines",
    "PN": "Pitcairn",
    "PL": "Poland",
    "PT": "Portugal",
    "PR": "Puerto Rico",
    "QA": "Qatar",
    "RE": "Reunion",
    "RO": "Romania",
    "RU": "Russian Federation",
    "RW": "Rwanda",
    "BL": "Saint Barthelemy",
    "SH": "Saint Helena",
    "KN": "Saint Kitts And Nevis",
    "LC": "Saint Lucia",
    "MF": "Saint Martin",
    "PM": "Saint Pierre And Miquelon",
    "VC": "Saint Vincent And Grenadines",
    "WS": "Samoa",
    "SM": "San Marino",
    "ST": "Sao Tome And Principe",
    "SA": "Saudi Arabia",
    "SN": "Senegal",
    "RS": "Serbia",
    "SC": "Seychelles",
    "SL": "Sierra Leone",
    "SG": "Singapore",
    "SK": "Slovakia",
    "SI": "Slovenia",
    "SB": "Solomon Islands",
    "SO": "Somalia",
    "ZA": "South Africa",
    "GS": "South Georgia And Sandwich Isl.",
    "ES": "Spain",
    "LK": "Sri Lanka",
    "SD": "Sudan",
    "SR": "Suriname",
    "SJ": "Svalbard And Jan Mayen",
    "SZ": "Swaziland",
    "SE": "Sweden",
    "CH": "Switzerland",
    "SY": "Syrian Arab Republic",
    "TW": "Taiwan",
    "TJ": "Tajikistan",
    "TZ": "Tanzania",
    "TH": "Thailand",
    "TL": "Timor-Leste",
    "TG": "Togo",
    "TK": "Tokelau",
    "TO": "Tonga",
    "TT": "Trinidad And Tobago",
    "TN": "Tunisia",
    "TR": "Turkey",
    "TM": "Turkmenistan",
    "TC": "Turks And Caicos Islands",
    "TV": "Tuvalu",
    "UG": "Uganda",
    "UA": "Ukraine",
    "AE": "United Arab Emirates",
    "GB": "United Kingdom",
    "US": "United States",
    "UM": "United States Outlying Islands",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VU": "Vanuatu",
    "VE": "Venezuela",
    "VN": "Vietnam",
    "VG": "Virgin Islands, British",
    "VI": "Virgin Islands, U.S.",
    "WF": "Wallis And Futuna",
    "EH": "Western Sahara",
    "YE": "Yemen",
    "ZM": "Zambia",
    "ZW": "Zimbabwe"
}

# APAC countries for regional analysis
APAC_COUNTRIES = [
    "CN", "IN", "JP", "KR", "AU", "SG", "MY", "TH", "VN", "ID"
]

# Color scheme for visualization
COLOR_SCHEME = {
    "us": "hsl(221, 83%, 53%)",
    "cn": "hsl(0, 84%, 60%)",
    "focusCountry": "hsl(36, 96%, 50%)",
    "primary": "hsl(var(--primary))",
    "secondary": "hsl(var(--secondary-foreground))",
    "academic": "hsl(221, 83%, 53%)",
    "corporate": "hsl(330, 80%, 60%)",
    "rest": "hsl(330, 60%, 30%)",
    "spotlight": "hsl(48, 96%, 50%)",
    "oral": "hsl(142, 71%, 45%)",
    "papers": "hsl(200, 65%, 50%)",
    "authors": "hsl(280, 55%, 55%)",
    "US": "hsl(221, 83%, 53%)",
    "CN": "hsl(0, 84%, 60%)",
    "GB": "hsl(120, 70%, 45%)",
    "HK": "hsl(300, 75%, 50%)",
    "SG": "hsl(180, 80%, 50%)",
    "CA": "hsl(15, 85%, 55%)",
    "DE": "hsl(45, 90%, 50%)",
    "KR": "hsl(270, 75%, 50%)",
    "FR": "hsl(240, 80%, 55%)",
    "CH": "hsl(135, 70%, 45%)",
    "UK": "hsl(90, 65%, 50%)",
    "AU": "hsl(315, 80%, 55%)",
    "JP": "hsl(195, 85%, 50%)",
    "UNK": "hsl(0, 0%, 60%)",
    "IL": "hsl(210, 75%, 50%)",
    "IT": "hsl(105, 70%, 50%)",
    "NL": "hsl(255, 80%, 55%)",
    "AE": "hsl(30, 85%, 55%)",
    "TW": "hsl(165, 75%, 50%)",
    "AI": "hsl(285, 80%, 55%)",
    "IN": "hsl(36, 96%, 50%)",
    "AT": "hsl(60, 85%, 50%)",
    "RU": "hsl(330, 75%, 50%)",
    "DK": "hsl(225, 80%, 55%)",
    "SE": "hsl(75, 70%, 50%)",
    "SA": "hsl(345, 85%, 55%)",
    "BE": "hsl(150, 75%, 50%)",
    "ES": "hsl(300, 70%, 50%)",
    "FI": "hsl(120, 80%, 45%)",
    "MO": "hsl(270, 85%, 55%)",
    "GR": "hsl(195, 75%, 50%)",
    "VN": "hsl(45, 80%, 55%)",
    "BR": "hsl(105, 85%, 50%)",
    "PL": "hsl(315, 75%, 50%)",
    "CZ": "hsl(165, 80%, 50%)",
    "NO": "hsl(240, 75%, 55%)",
    "CL": "hsl(285, 70%, 50%)",
    "TR": "hsl(15, 80%, 55%)",
    "PT": "hsl(135, 75%, 50%)",
    "EU": "hsl(210, 85%, 50%)",
    "BG": "hsl(75, 80%, 50%)",
    "LU": "hsl(330, 80%, 55%)",
    "IR": "hsl(180, 75%, 50%)",
    "NZ": "hsl(255, 85%, 55%)",
    "PH": "hsl(60, 75%, 50%)",
    "ZW": "hsl(120, 70%, 50%)",
    "IE": "hsl(345, 80%, 55%)",
    "CX": "hsl(195, 80%, 50%)",
    "MY": "hsl(270, 75%, 55%)",
    "CO": "hsl(30, 80%, 55%)",
    "KP": "hsl(150, 80%, 50%)",
    "SI": "hsl(285, 75%, 50%)",
    "AC": "hsl(45, 85%, 55%)",
    "TH": "hsl(105, 80%, 50%)",
    "RE": "hsl(315, 85%, 55%)",
    "UY": "hsl(165, 75%, 50%)",
    "AM": "hsl(240, 80%, 55%)",
    "IO": "hsl(75, 85%, 50%)",
    "CY": "hsl(330, 75%, 50%)",
    "TD": "hsl(195, 75%, 55%)",
    "NA": "hsl(255, 80%, 50%)",
    "HR": "hsl(60, 80%, 55%)",
    "EG": "hsl(120, 85%, 45%)"
}

# Institution type classification keywords
ACADEMIC_KEYWORDS = [
    "university", "institute", "college", "school", "academia", "research institute",
    "iit", "iisc", "iiit", "nit", "bits", "tifr", "isi", "jnu", "du", "bhu"
]

CORPORATE_KEYWORDS = [
    "microsoft", "google", "facebook", "meta", "apple", "amazon", "ibm", "intel",
    "nvidia", "adobe", "salesforce", "uber", "netflix", "twitter", "linkedin",
    "tcs", "infosys", "wipro", "hcl", "tech mahindra", "cognizant", "accenture",
    "research", "labs", "laboratory", "r&d", "development"
]

# Status mappings for paper types
STATUS_MAPPINGS = {
    "oral": ["oral", "accept (oral)", "oral presentation"],
    "spotlight": ["spotlight", "accept (spotlight)", "spotlight presentation"],
    "poster": ["poster", "accept (poster)", "poster presentation", "accept"],
    "workshop": ["workshop", "workshop paper"],
    "demo": ["demo", "demonstration"],
    "unknown": ["unknown", "", None]
}

# Default configuration for analytics generation
DEFAULT_CONFIG = {
    "focus_country_code": "IN",
    "focus_country_name": "India",
    "include_unknown_countries": True,
    "min_papers_for_country_inclusion": 1,
    "institution_analysis_enabled": True,
    "review_statistics_enabled": True,
    "citation_analysis_enabled": False,  # May not be available in all datasets
}

# Dashboard configuration templates
DASHBOARD_SECTIONS = {
    "summary": {
        "title": "Research Impact Overview",
        "template": [
            "{country} contributed {paper_count} research papers to {conference} {year}, representing {percentage}% of the conference's total accepted works and ranking {rank} globally among contributing nations.",
            "{country} researchers demonstrated strong research leadership with {first_author_percentage}% of papers featuring {country} first authors, indicating significant intellectual contribution to the global machine learning discourse.",
            "The research quality is evidenced by a {spotlight_percentage}% spotlight acceptance rate, with {spotlight_count} paper(s) receiving this prestigious recognition among the conference's most impactful contributions.",
            "{country}'s machine learning ecosystem comprises {author_count} unique researchers across {institution_count} institutions, with a balanced representation of {academic_count} academic institutions and {corporate_count} corporate research entities."
        ]
    },
    "context": {
        "title": "Global Research Landscape",
        "subtitle": "{country}'s position within the international machine learning research community and comparative analysis with leading nations.",
        "template": [
            "The global research landscape is led by the United States ({us_percentage}% of papers) and China ({cn_percentage}%), followed by the United Kingdom ({gb_percentage}%) and Germany ({de_percentage}%), with {country} contributing {percentage}% of total research output.",
            "{country} ranks {rank} globally in research volume, positioning it as an emerging contributor in the international machine learning research ecosystem with substantial growth potential.",
            "Within the Asia-Pacific region, {country} trails China, South Korea, Singapore, and Hong Kong in absolute research contributions, highlighting opportunities for enhanced regional collaboration and capacity building."
        ]
    },
    "focusCountry": {
        "title": "{country} Research Ecosystem Analysis",
        "subtitle": "Detailed examination of authorship patterns, collaboration dynamics, and research leadership within {country}'s machine learning community.",
        "template": [
            "{country} researchers exhibit strong research independence with {majority_percentage}% of papers having majority {country} authorship, indicating substantial domestic research capacity and reduced dependence on international collaboration.",
            "The {first_author_percentage}% first authorship rate demonstrates {country} researchers' leadership in conceptualizing and driving research projects, reflecting growing confidence and expertise in the field.",
            "With {author_count} unique authors contributing across {paper_count} papers, {country} maintains an efficient author-to-paper ratio of {ratio}, suggesting productive individual contributions and effective research mentorship."
        ]
    },
    "institutions": {
        "title": "Institutional Research Excellence",
        "subtitle": "Comprehensive evaluation of {country}'s academic and corporate institutions contributing to machine learning research excellence.",
        "template": [
            "The {top_institution} emerges as the national leader with {top_papers} papers and {top_authors} authors, including the country's {spotlight_info}, demonstrating exceptional research quality and productivity.",
            "Academic institutions dominate {country}'s research landscape with {academic_percentage}% representation ({academic_count} of {total_institutions} institutions), while corporate research centers contribute {corporate_percentage}%, indicating strong university-led research culture.",
            "The institutional diversity spans premier engineering institutes (IITs), specialized research universities (IISc), and corporate R&D centers, creating a robust ecosystem for sustained machine learning research growth."
        ]
    }
}
